### ISSUE TITLE
New boat pic needs  "main" property set to true

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#101]
When a new boa is created all pictures "main" property is set to false causing there to be no picture showing on the main site boats page.

**Comment by bschmitz9** [comment]
@dolson334 I added this for units and boats in the admin site. I'm just adding it to the "newPictureInfo" object when you add the new photo... newPictureInfo.isMain = this.isMainPhoto. If they don't have a photo that has been checked as the main we're going to have to fall back to a default..like the first one in the array or something?

Can you make sure the isMain property is on every photo then, either true or false.

**Comment by dolson334** [comment]
@bschmitz9 Isnt it now?

**Comment by bschmitz9** [comment]
@dolson334 Yea it is right now..just don't want you to change it.
