### ISSUE TITLE
Updating a boat doesn't update the boat on the admin site.

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#108]
1. Add a new boat photo to an existing boat. 
2. Approve the change in the preview site.
3. Go back to the boat in the admin site. Photo count and photo image should be updated to include the newly added photo(s).

**Comment by dolson334** [comment]
@bschmitz9 this is the same issue as 107. We need the right params passed to the back end.

**Comment by bschmitz9** [comment]
I'm going to close this one if its the same issue as 107 and we can work from that one for now.
