### ISSUE TITLE
Update saved unit and boat video to be the full file

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#109]
Currently a previously saved unit or boat video doesn't play in the edit modal. Only newly added videos that haven't been saved to the database are playing. I believe that is because previously I was just sending back the actual video file path. But I think I need the full file so that I can pass it into URL.createObjectURL without errors. Basically just need to update the database to make sure the full file is being saved.

Steps to replicate:
Add a new video.
Save your updates. 
Check the modified object in the units and boats component. I've already updated it just make sure the full video file is being returned with the initial getUnits and getBoats call on page load.

**Comment by dolson334** [comment]
@bschmitz9 you dont need the CreatUrlObject..I fixed in the edit component with the code belo. 

```
this.savedmp4Video = this.currentVideo[0].mp4Dir;
this.savedwebmVideo = this.currentVideo[0].webmDir;
```
