### ISSUE TITLE
Updating a unit / boat video doesn't update isVideoStaged on the unit / boat preview page

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#110]
Steps to replicate:

1. Add or update video for a unit or boat.
2. Go to the preview page - isVideoStaged is true for Units and Boats page. But then when I click to view the change isVideoStaged is false for the Unit and Boat page so no red border or preview styling is showing.

**Comment by dolson334** [comment]
@bschmitz9 when looking at the actual video you should be looking or isStaged and or isNew like you do for a picture. isVideoStaged and isPictureStaged are only for identifying if a unit has any pending changes with their pictures and/or videos.

**Comment by bschmitz9** [comment]
@dolson334 looks to be working fine if you add a video to an existing unit that did not previously have a video. The issue:

1. Delete an existing video from an existing unit.
2. Add a new video.
3. Go to preview the unit on the Unit page. Check the unit. It has 3 videos in the videos array, the first video in the array (unit.videos[0]) has isStaged set to false. The next two have isStaged set to true. There should be just one video in that array so we can access it with [0]. I'm already checking "unit.videos[0].isStaged === true" in the html.

**Comment by dolson334** [comment]
@bschmitz9 should be working now. Only returns one video.
