### ISSUE TITLE
Adding a new boat or unit is breaking the page when saving

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#124]
Endpoint breaks when I try to add a new unit or boat.

**Comment by dolson334** [comment]
@bschmitz9 This works for me...Can you try again with a clean rebuild?

**Comment by bschmitz9** [comment]
@dolson334 console error reads: 

Failed to load resource: the server responded with a status of 500 () 
:8080.resortplatform...dpoint/upsertunit:1

**Comment by bschmitz9** [comment]
@dolson334 it doesn't break if I update text. Looks to be an issue when I add a picture. But when I'm updating something like bedrooms, cost, etc the unit is removed from the page after it reloads. 

Also, if there is a preview to approve text changes then the text shouldn't update right after saving in the admin page. Shouldn't be updated until it is approved in the preview.

**Comment by bschmitz9** [comment]
@dolson334 same thing for boats

**Comment by dolson334** [comment]
@bschmitz9 I was able to recreate with you latest pull. If you pull it should be working now.
