### ISSUE TITLE
Updating details for photos

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#125]
Process:

1. Update details only for fishing photos
2. View & Approve Changes button appears, triggering preview functionality.
3. Go to preview page - isNew and isStaged are both true for that photo.

Issue: isNew should be false. Right now the preview is showing the photo as new which isn't right. 

Is there a way for me to tell if only the text was changed so I can say something like "Details Updated"?

**Comment by dolson334** [comment]
@bschmitz9 Yea, isNew should be false. Working on that now.

**Comment by dolson334** [comment]
@bschmitz9 I made some changes and his is what you can use now:

new picture:  isNew = true;
updated picture: isPictureStaged = true;
edited details: (isStaged = true && isPictureStaged = false && isNew = false)
