### ISSUE TITLE
Playing and Deleting a Unit Video

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#126]
@dolson334 double check functionality to delete an existing video and then add it as well. 

if modified.deleteSavedVideo is true, then remove the last saved video regardless.
if modified.video is there then also add this newly saved video to the database.

Just make sure the deleted video is being removed and the new video (if added) is taking its place.

Also, a newly added video doesn't play. It just spins on the unit preview page. And it doesn't show if you add a video then edit unit, and click "View/Delete"..any ideas why? It's like the ones that are pre-saved in the database when I build the database play fine. But the ones that I add won't play although they look to be the same. Are you seeing this on your end?

**Comment by dolson334** [comment]
@bschmitz9 in the admin page if you add a video to a unit that does not have one... the currentUnit.action.modified does not return the base64 string like it does for a picture from the edit modal. instead the value it returns is 
video: {mp4: File(8854562), webM: File(7187868)}__proto__: Object

@bschmitz9  can u fix this?

**Comment by bschmitz9** [comment]
@dolson334 I changed the video object because of the issue I mentioned above. I can change it back but I wasn't seeing videos playing if you follow the steps above. I can change it back but its not working correctly, atleast on my end

**Comment by dolson334** [comment]
@bschmitz9 yea thats due to a separate issue. Once you fix this assign it back to me.

**Comment by bschmitz9** [comment]
@dolson334 ok I made the update back to just the path to play the video. Check all the video functionality to make sure videos are being deleted and updated correctly and are playing on the main site. I'll update the stying of the buttons in the video modal soon so they're not over lapping the video.

**Comment by dolson334** [comment]
@bschmitz9 can u change this to just pass back the base64 string like we do for pictures?

**Comment by bschmitz9** [comment]
@dolson334 I'll have to look into this. I'm not sure. Its a video not a picture so I don't know if it has a base64 or what

**Comment by dolson334** [comment]
@bschmitz9 another option would be for you to write the picture to some temp directory and pass that back. I can get the base64 from there.

**Comment by dolson334** [comment]
@bschmitz9 actaully hold off on this for now. I have something I can try.

**Comment by dolson334** [comment]
@bschmitz9 ok, here is what you can do. I created a function awhile ago in javascript called convertFileToBase64. Its in the about-edit.component.ts. Here you can send in a file and the Id of a property and it will set the base64 to the "src" of that property. This will work with a video as well. You can do this instead of creating the URL and jus use the file object (this.mp4).

**Comment by dolson334** [comment]
@bschmitz9 Actually, I will do this.

**Comment by dolson334** [comment]
@bschmitz9 Ok I got the video being updated and playing correctly. There may be a few other issues with Video and staging but I will wrote those up.
