### ISSUE TITLE
Changes 

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#127]
Can you just pass the pageUpdates with the getPictures call for if we are approving all? For example, currently, when I approve one picture it calls the endpoint with the pageUpdates and I approve. But then the getPictures is called again with the pageUpdates. 

I think we should only pass back the pageUpdates in adminSite service if we are approving all.  

Does that make sense?

**Comment by bschmitz9** [comment]
@dolson334 closing this its the same thing as #130
