### ISSUE TITLE
Need a ? in admin and pending pages

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#128]
When in the admin/pending pages the picture dirs need an added ?. This is to refresh the cache. Otherwise pics wont update. Dont need on main site. 

`	

	public getPictureDir(picture: Photo){
		return picture.dir + "?timestamp=" + new Date().getTime();
	}

`

**Comment by dolson334** [comment]
Need on models as well

**Comment by bschmitz9** [comment]
@dolson334 I added this to resort and fishing photos admin and preview, and then the edit modal as well..where else do we need it? those are the only places I see you using that getPictureDir function so far.

**Comment by dolson334** [comment]
@dolson334  anywhere on the admin or pending pages where a dir is references (wouldnt hurt to do everywhere I guess but its not needed on the main site). Be sure to note though that the getPictureDir fucntions are a little different on the pending vs the admin pages.

**Comment by bschmitz9** [comment]
@dolson334 I'm not going to do anything with the getPictureDir function. I'll just go through and add the "?". The preview page / main site page is the same thing so both the "preview" and the "live" site will have the question mark.
