### ISSUE TITLE
Create the bantor database

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#13]
I can get you the scripts for this. when you are ready.

**Comment by dolson334** [comment]
@dolson55 I added a database backup file to a new directory (bantor/database/bantorBackup.bak).  Look up how to restore a database with a backup file. Comment on here with any issues.

**Comment by dolson334** [comment]
@dolson55 were is this at.

**Comment by dolson55** [comment]
getting there.  Had an issue with SSMS but I think I figured it out

**Comment by dolson55** [comment]
So I discovered that only a certain version of SSMS can run on windows 10.  I'll believe that's the issue.

**Comment by dolson55** [comment]
So I figured out my SSMS, but when I try and restore the backup, I get a message saying....
"Index was outside the bounds of the array. (Microsoft.SqlServer.Smo)"

**Comment by dolson55** [comment]
What version is your SSMS?? They need to be compatible to restore a database.

**Comment by dolson55** [comment]
Nevermind.  I figured it all out. Because I'm running on a Bootcamp version of windows my .NET configurations weren't updated to 3.5 to support my SSMS (I don't know why that was needed but whatever).  I have successfully restored bantor to my SSMS so I'm all good.
