### ISSUE TITLE
isMain Checkbox

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#131]
Replicate:

1. Create a new boat.
2. Approve the boat.
3. All pictures isMain is false. One needs to be true. Also, can you make this a boolean rather then a string value.

Also, editing an existing photo to be the new main photo needs to update the display to show that photo as the main photo.

**Comment by bschmitz9** [comment]
@dolson334 needs to be same for units as well.

**Comment by dolson334** [comment]
@bschmitz9 this should be there now. You may have to tweak the html a bit but maybe not.
