### ISSUE TITLE
Only highlight fields that changed

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#136]
So I added a JSONObject to each object (Unit, Boat, Picture, etc...). Its called "stagedValues". If the property is in stagedValues, then it is staged. So you could create a function where you simply check if the value is there.

**Comment by dolson334** [comment]
@bschmitz9  i created getText in the utility.

**Comment by bschmitz9** [comment]
@dolson334 No need for a getText function..I can just check the object directly in the html. But I need a way to check if the boat, unit, picture, etc is a newly created on..right now isNew remains false.

**Comment by dolson334** [comment]
@bschmitz9 is this done?

**Comment by bschmitz9** [comment]
@dolson334 no I  need a way to know if the unit or boat, etc is a newly added one. isNew remains false. The editing and existing item looks to be working fine.

**Comment by dolson334** [comment]
K assign me

**Comment by bschmitz9** [comment]
@dolson334 it is assigned to you. if your pictures is next to the ticket its assigned to you.

**Comment by dolson334** [comment]
@bschmitz9 k try this now to see if this shows like you are expecting. If so comment on here.

**Comment by bschmitz9** [comment]
@dolson334 working better. But if its a newly added unit (or anything) can you switch the other properties to false..so isPictureStaged and isStaged are both false. I only need to know if its a newly added item. And if they are editing keep the properties as you have them. So if isNew is true, set the others to false.

**Comment by dolson334** [comment]
@bschmitz9 ok try this now and close if it works.
