### ISSUE TITLE
ContactUs preview page needs to be set up

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#137]
The approve buttons arent passing back the pageUpdates and the staged picture isnt highlighted red

**Comment by bschmitz9** [comment]
@dolson334 I updated the contact us. If updating just one section (either picture or contact info) right now I just have one function called approveContactData. I'm passing a parameter called "sectionEditing" that is either "picture" or "contact-info". Can you update whichever section is being passed to the backend? 

If clicking "Approve All" I just have a function called "approveAll" like is on those other pages.

**Comment by bschmitz9** [comment]
@dolson334 social media links need to trigger page updates and then be added to stagedValues on the preview page.

**Comment by bschmitz9** [comment]
@dolson334 contact us is returning back to the preview page when there are no more pending changes. It should go back to the admin page. I don't see any sort of property on that response similar to something like we have for fishing photos with response.arePicturesStaged.

**Comment by dolson334** [comment]
@bschmitz9 remaingPendingChanges should be working properly now.

**Comment by dolson334** [comment]
@bschmitz9 why are you passing back the resort in the approveContactData... I dont think that is needed.

**Comment by bschmitz9** [comment]
@dolson334 pass back what ever you would like to update the page doesn't matter to me

**Comment by bschmitz9** [comment]
@dolson334 I updated the names. But updating a social media link breaks the page after saving.

**Comment by bschmitz9** [comment]
@dolson334 also updating any changes on the preview page doesn't update the text when back on the admin page

**Comment by dolson334** [comment]
@bschmitz9 I think we are all set here now. Test it and let me know if I missed something
