### ISSUE TITLE
All preview pages need to check if intro pageTexts are staged 

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#138]

**Comment by bschmitz9** [comment]
@dolson334 I pushed this. Let's make sure its working fine for contact us before I go on to the other pages. Right now I'm not seeing any approved changes taking effect when the preview page reloads or when I'm sent back to the admin page.

And if they "Approve All" then include the header update in that as well. 

If the section they approve is "page-intro" just send back whatever the latest header and intro paragraph is.

Let me know.

**Comment by bschmitz9** [comment]
@dolson334 "Approve All" updates the header and intro paragraph but it doesn't update if I just hit "Approve" on that specific section.

**Comment by bschmitz9** [comment]
@dolson334 contact us works great for updating the intro via the "Approve" or "Approve All" button.

The rest need to be set up - "Approve" and "Approve All"

**Comment by dolson334** [comment]
finished blog
