### ISSUE TITLE
Pending and Current Items Stay in the same order

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#139]
The preview page and the live / admin site for items (boats, pictures, etc) need to stay in the same order.

**Comment by bschmitz9** [comment]
New items get pushed to the front.

**Comment by dolson334** [comment]
@bschmitz9 I would think new items should be in the front. 

Can you send me a recreation path?

**Comment by bschmitz9** [comment]
@dolson334  Yea they should be in the front. That’s what I said in the comment above. If they edit an existing item it should stay where it was before. 

What’s a recreation path?

**Comment by dolson334** [comment]
@bschmitz9 Ok ill look into this.

**Comment by dolson334** [comment]
@bschmitz9 so for pictures.. if I edit text of a fishing picture it comes to the front on the preview page.. which seems right to me... then when I approve changes it stays where it was before.. was this not what you were thinking? 

If we stage something it seems like it should come to the front.

**Comment by bschmitz9** [comment]
@dolson334 I don’t know..leave it then and we can get feedback from users. I think we need something in the admin that tells us if the picture or unit or boat or whatever has pending changes..when I update something in the admin and the page reloads I don’t even know what I just updated and then all of a sudden the pictures are in different places. It’s confusing.
