### ISSUE TITLE
Updating photo details for a second time doesn't update preview page

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#140]
Reproduce:

1. Update photo details and save. 
2. See preview page but don't approve anything. 
3. Go back to admin and update the same details again. 
4. Go back to preview page, the updated text does not show up until you approve the change. 

Editing the actual photo this same way works great.

**Comment by bschmitz9** [comment]
even after you approve the changes and go back and edit the same details again the preview page shows the red border but does not show updated text.

**Comment by bschmitz9** [comment]
updating just details breaks the picture in the preview page.

**Comment by bschmitz9** [comment]
@dolson334 when adding a new photo the picture doesn't show up on the preview page. It breaks

**Comment by dolson334** [comment]
@bschmitz9 these should all be fixed now.

**Comment by bschmitz9** [comment]
@dolson334 this doesn't work for the first update now.

If I make an update and then go to the preview change the updated text isn't there. If I just approve it and go back to the admin the updated text is there.
