### ISSUE TITLE
Fishing Photo returns back to preview page when there are no more pending changes

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#141]
Update one fishing photo - picture or description.
Approve the change in the preview.
The page is returning back to the preview page, it needs to return to the admin page.

**Comment by bschmitz9** [comment]
When approving all fishing photos the page returns back to admin as it should but the "View & Approve Changes" button is still there. 

Cause: areFishingPhotosStaged is still true. 

I think this is probably related to my above comment - the code thinks there are stillPendingChanges when there aren't any.

**Comment by dolson334** [comment]
@bschmitz9 working now
