### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#142]
Capacity value doesn't show up on admin or preview page - there is no property called occupants.

The Motor value doesn't show up on the preview page when it is updated. The old value remains.

**Comment by dolson334** [comment]
@bschmitz9 I fixed this. You will need to fix the edit modal for the occupants.

**Comment by bschmitz9** [comment]
@dolson334 updating just capacity doesn't trigger a preview option in the admin.

no text is getting updated on the boat page - so if I update the boat price, motor, etc and go to the boats preview page I see the text updated but then if I click into that boat the text is the old text.

**Comment by bschmitz9** [comment]
@dolson334 same with the unit page.

**Comment by dolson334** [comment]
@bschmitz9 on the boats page in the "updateExistingBoat" function currentBoat.action.modified is showing capacity as undefined from the edit modal. Can you fix this?

**Comment by dolson334** [comment]
@bschmitz9 this should be fixed now for boats. You just need to fix the comment I said above.  Fixing for units now.

**Comment by bschmitz9** [comment]
@dolson334 ok I updated the modified object. Pull and update to make the capacity update trigger the preview.
