### ISSUE TITLE
Units and Boats approve all

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#143]
I updated the Units and Boats approve all to run through the component, like I did with photos. It was working after the change I made. But you can set those up now.

**Comment by dolson334** [comment]
@bschmitz9 just an fyi you have to be wary of what endpoints your calling from the service you copied the call from picture to units. so units is calling the getpictures endpoint.

**Comment by bschmitz9** [comment]
@dolson334 I know it was. I'm not touching the endpoint code I don't know what endpoint does what. I'll let you update the service

**Comment by dolson334** [comment]
@bschmitz9 ok. do we need to call the function in javascript approveAllPictures on the units page?

**Comment by bschmitz9** [comment]
@dolson334 yes. That will approve all the units at one time

**Comment by dolson334** [comment]
@bschmitz9 just kinds weird name since we may be approving more than just picture. can you just call it "approveAll"?

**Comment by bschmitz9** [comment]
@dolson334 yea that's fine. I'll change it after you finish it

**Comment by dolson334** [comment]
@bschmitz9  ok

**Comment by dolson334** [comment]
@bschmitz9 done
