### ISSUE TITLE
Updating Contact Us Intro causes preview page to say false

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#145]
If you update the page header or the page introduction paragraph and go to the preview page the header and the intro paragraph just say false.

**Comment by bschmitz9** [comment]
@dolson334 I also don't see the page header or the intro paragraph in the stagedValues object when updated. you can get the text however you'd like but I just need to know what in the intro has been updated so I can show the red border and the approve / decline buttons.

**Comment by dolson334** [comment]
@bschmitz9  should be all set now. For the border you need to check the pageText isStaged boolean to determine if its staged. The getPageText function only returns the dir. Maybe create a new function that returns the actual pageText.
