### ISSUE TITLE
New Names For Social Media Links

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#146]
@bschmitz9 I renamed all of our link keys to include "contactUs". So facebookLink is now contactUsFacebookLink. Can you update all of the javascript and html to include the "contactUs" text. Im not sure what I should and shouldnt be changing with the editModal etc.. you know. 

This is needed for the backend. Makes things cleaner for staging/unstaging.

**Comment by bschmitz9** [comment]
@dolson334 I updated the names. But updating a social media link breaks the page after saving.
