### ISSUE TITLE
Contact Us Preview Page Social Media Links Outline

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#151]
If you update just a link I there is no red outline anywhere on the preview page.

**Comment by bschmitz9** [comment]
@dolson334 red outline is set up for pending social media links. The Approve button in the address / contact information section is not updating the links. Those buttons should approve everything in that section if it is clicked. Then declining would then decline all changes in that section. If there are no more pending changes in the intro or background pic than the page redirects back to the contact us admin.

**Comment by dolson334** [comment]
@bschmitz9 If I edit one of the links and that it there is no red outline on the preview page.

**Comment by dolson334** [comment]
@bschmitz9 the approve all should now update the links.

**Comment by bschmitz9** [comment]
@dolson334 forgot to push that update. I just pushed so it should be there now. Contact Us looks good all around. Test more later. Closing this.
