### ISSUE TITLE
Login Security

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#165]
Need to properly ensure the user is logged in with each admin and pending page request

**Comment by dolson334** [comment]
@bschmitz9 I implemented the login token.. this will really make things easy.. basically we will no longer need the resortAlias in the adminSite. 

After you login the token will be returned in an alert. Every admin/pending page request will need this token. After you add that assign this back to me and I will complete.

**Comment by bschmitz9** [comment]
@dolson334 I added this but can we just do this within the routes? If someone isn't logged in we don't want them getting to any of the admin pages at all. They shouldn't be able to even see the page if they aren't logged in. We don't want to check once they're in the process of making an update. So the way I have it now I am just checking to see if there is a current valid token as the route (page) is changing. If there is a token they're logged in and they can access the requested page. If there isn't a token then it redirects them back to the login screen. This way we already know if they have the credentials to update the page before they get to the page.

We can keep resortAlias in each page or add the token to each page if you need it to associate the data with a resort on the backend.

And yea Local Storage Service seemed to be the most common way to pass the token so I did that.

**Comment by dolson334** [comment]
@bschmitz9 thats fine, but I also will need the token in every request for a couple reasons.

1. The token can only be verified on the server side with this algorithm I downloaded. 
2. Any user could use a program like PostMan which just makes requests and they could bypass the login. So every requests needs a token with it so I can say "yes I created this token on the backend and you can access data". 

So just where you are passing the resortAlias pass the logintoken on each screen.

**Comment by dolson334** [comment]
@bschmitz9 I added the token to the getUnits call in the admin site and removed the resortAlias. Works great. You can now add this token and remove all resortAlias in the adminCalls.

**Comment by bschmitz9** [comment]
@dolson334 updated all the other pages to have the token - home, settings, stories, resort photos, contact us,. All of them.

**Comment by dolson334** [comment]
@bschmitz9 the only one that still needs to be tested is the aboutUs.. we need to get that page working.
