### ISSUE TITLE
Create files for every table 

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#17]
Create a dir in bantor/database called sqlTables.

In this dir create a new sql file for every database:
1.  We need the table create scripts in each file. 
2. To get the create script right click on the table --> Script table as --> Create to --> file --> select one of  your new sql files

So when your done, for each sql table in bantor there should be a file in bantor/database containing that tables create scripts.

**Comment by dolson55** [comment]
Take a look at what I just pushed.  Is this what you're looking for?

**Comment by dolson334** [comment]
Yes. 
1. rename the tables to get rid of the "dbo."
2. Get rid of everything above the create table

**Comment by dolson55** [comment]
All set.  Let me know if you need anything otherwise I'm closing this.

**Comment by dolson334** [comment]
Looks good. Go ahead and close.

**Comment by dolson334** [comment]
@dolson55 is there a reason you havnt closed this one?
