### ISSUE TITLE
When creating a new unit, main photo doesn't load in preview

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#173]
If you add a new unit and preview it the main unit picture doesn't show up.

**Comment by bschmitz9** [comment]
@dolson334 but picture loads fine if you approve the unit and see it back in the admin site

**Comment by dolson334** [comment]
@bschmitz9 did you click an is main check box on any of the pictures? it works for me if I click the is mai check box.

**Comment by bschmitz9** [comment]
@dolson334  there should be a default if they don't click the isMain checkbox..so if not checked take the first photo and make it the main photo by default.
