### ISSUE TITLE
Picture order jumps all over the place between admin and preview/main site.

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#175]
I think its fine to leave the pending picture updates at the front. but once I approve one change it goes to the end, and then if I come back to view a different pending photo, the last updated photo moves back to the front behind to the pending photo.

**Comment by dolson334** [comment]
@bschmitz9 take a look at this now for the picture pages. I am no longer pushing staging changes to the front. Everything should just stay the same. Take a look to see if this is what you were looking for.

**Comment by bschmitz9** [comment]
@dolson334 yea I think this is better at least initially
