### ISSUE TITLE
Set Up Page Intro Preview

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#179]
You can set up the intro preview for blog, stories, fishing photos, resort photos, contact us, and units. 

I'm working on boats. We'll probably want to allow intro preview for fishing reports right?

**Comment by dolson334** [comment]
@bschmitz9 yea we probably should.

**Comment by bschmitz9** [comment]
@dolson334 boats intro preview is ready

**Comment by dolson334** [comment]
**Intro done for:**
Blog
Stories
Boats
