### ISSUE TITLE
Fishing Reports Intro Preview

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#180]
Intro preview functionality needs to be set up in the fishing reports admin so the preview page can be accessed.

**Comment by dolson334** [comment]
@bschmitz9 I think we should not allow them to preview anything on fishing reports. If the object (in this case fishing report) is not preview enabled they shouldnt be able to preview anythig.

**Comment by bschmitz9** [comment]
@dolson334 aren't we doing that for every page already? If prevewEnabled is false everything should just go live right away. I don't know if it makes much sense to have all the intros previewAble but the reports, seems kind of confusing but we can leave it and see what feedback is I guess.
