### ISSUE TITLE
Social Media links not working on main site

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#187]

**Comment by dolson334** [comment]
@bschmitz9 Can u do this? Here are the the text keys values. Its for the social media links on all pages. 

<img width="252" alt="socialMediaLinks" src="https://user-images.githubusercontent.com/16144247/54232802-87e47880-44d9-11e9-9db2-fad6c821e38d.png">

**Comment by bschmitz9** [comment]
@dolson334 I have those values there. The footer links are set in the footer component within the mainSite folder. "this.resort" is undefined within getPageText when that page loads now so it never finds the matching keys to return a value. We were getting the resort values through a resortLight call previously:

`	this.resort = this.pageSetupService.getResortLight();`

What do we need to adjust to do here to get a value for the resort?

**Comment by dolson334** [comment]
@bschmitz9 is there a way to pass the this.resort into the footer component? I would prefer not make another endpoint call if we dont have it.

**Comment by bschmitz9** [comment]
@dolson334 going to need the resort info when the main site home page loads up. This footer component loads with that page (and every page). So how are you going to load the correct data from the backend for each resort? Need to figure that out first. We we're going to do this by getting the resort name in the URL previously.

**Comment by dolson334** [comment]
@bschmitz9 I put the resortLight in localstorage. Then I use that in the footer.
