### ISSUE TITLE
Setup Reservation Other Site Link

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#188]
@bschmitz9 I created a method in the utilities service called "getAppSetting". You can call that with the key "reservationLink". If that key exits then you want to use that link. For MooseLake a have it set as "www.google.com". Just need you to setup the html and javascript.

**Comment by bschmitz9** [comment]
@dolson334 ok you can the updateReservationLink function in the admin site to set this up. Just send the saved link back in the main site and I'll use it on the unit and boat main site. Right now it is just taking you to Google.

**Comment by bschmitz9** [comment]
@dolson33 I can't get the "resort.response" value to pass into that appSettings function. Can you add that response to the unit and boat page in the main site like you have for blogs, etc. I should only have to call that getAppSetting in the unit and boat page to get the link they want to use right? That's the only place where it would link to the reservation system they want to use. You can save/update the link in appSettings on the backend via my message above.

**Comment by dolson334** [comment]
@bschmitz9 should be set for you to use now. Look for the alert.

**Comment by bschmitz9** [comment]
@dolson334 the endpoint for saving the reservation link in the admin is breaking. 

Go to unit reservations, input a new link, save. 
Same issue for boats.

I'm not able to get anything from the appSettings in the main site but I can try again after I clean.

**Comment by dolson334** [comment]
@bschmitz9 both updates work now. There is an alert on the main site unit page that will show the 'unitReservationLink' when you go there. You will need to make the same changes to the main site boat page looking for 'boatReservationLink'.. shouldnt take long.

**Comment by bschmitz9** [comment]
@dolson334 its set up in the main site but the saved URL needs to be absolute - i.e. **https://**www.google.com. Otherwise it'll break.

For the admin site on unit reservations and boat reservations I need to get "response.resort" if we're going to be passing the resort to get the saved link. You'll see an appSettings console error because "this.resort" is undefined.

**Comment by dolson334** [comment]
@bschmitz9 try this now.
