### ISSUE TITLE
Deleting a story in admin

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#198]
If I delete a story when there are only two remaining, both of the stories get deleted at the same time.

**Comment by bschmitz9** [comment]
@dolson334 I am seeing this happen for all pages.

**Comment by dolson334** [comment]
@bschmitz9 they are not being deleted. In this scenario, one story is being returned from the endpoint. Seems like something on the javascript/html side. I console.log(this.stories) and saw one story.
