### ISSUE TITLE
Handling delete of social media links

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#201]
@dolson334 How do we want to handle the removal of a social media link in the admin contact us? Deletion will just occur by removing the link from the input element in the edit modal. Right now if I clear the Facebook Link (or any link) and save it triggers the Preview button but the preview page doesn't have anything as staged.

**Comment by dolson334** [comment]
@bschmitz9 I think if we clear out a link I should just delete it on the backend. That would prevent the preview button from showing. Ill try that frst and see how it works.

**Comment by dolson334** [comment]
@bschmitz9 added. take a look when you get a chance.

**Comment by bschmitz9** [comment]
@dolson334 alright that works. I'm setting up the loading messages and alerts so that if they update only a link and save it (delete or change the link) it updates the website right away. But if they update any part of the page (contact info, background image, intro) then the preview loading messages and alerts show up. Does that work?

**Comment by bschmitz9** [comment]
@dolson334 They can also just click the icon in the admin to test the link too so if they just update a social media link and nothing else I don't think they need to go through the preview process.

**Comment by dolson334** [comment]
@bschmitz9 makes sense to me. Ill close.
