### ISSUE TITLE
Trying to change social media link breaks endpoint

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#205]
Change any social media link to another value and it breaks the endpoint. 500 error.

**Comment by dolson334** [comment]
@bschmitz9 I am not seeing this error.

**Comment by bschmitz9** [comment]
@dolson334 it's working but the inputs are being updated when the page reloads. Social media links can be updated right away with preview approval

**Comment by dolson334** [comment]
@bschmitz9 social media links should now be updating without preview.
