### ISSUE TITLE
Contact Us Preview button not showing 

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#208]
Recreation:
1. update the contact us backroud image. 
2. The view preview changes button not shown even the the this.isContactUsStaged is true.

**Comment by bschmitz9** [comment]
@dolson334 this works for me.

**Comment by dolson334** [comment]
Updated Recreation:
1. Edit a social media link
2. Edit the background image.
3. the preview button doesnt show.

**Comment by bschmitz9** [comment]
@dolson334 updating the contact background image breaks the endpoint. I can't test this right now.
