### ISSUE TITLE
Main Site - 400 error when trying to send contact message

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#213]
I get a 400 server error when trying to send a message through the contact form. Also, we should verify through your email or some email that contact messages are getting sent to the resort email address they have listed on the contact us page.

**Comment by bschmitz9** [comment]
@dolson334 same when trying to send through the home page and through the form in the footer.

**Comment by dolson334** [comment]
@bschmitz9 this looks like its working for me. We really need to sync up on this stuff. Its weird that I am seeing different results that you. Not really sure how that is possible. 

<img width="690" alt="emails" src="https://user-images.githubusercontent.com/16144247/54867633-6fcdee00-4d50-11e9-89e4-f178f3be25f9.png">
