### ISSUE TITLE
Blog and Fishing Report "Posted On" Date

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#214]
@dolson334 how are you saving the date when the blog is created. That date should automatically be generated and saved when each blog is created. Right now all the blogs just have today's date on them. The date coming from the database is today's date. Can you check this?

Check fishing reports date as well.

**Comment by dolson334** [comment]
@bschmitz9 the date comes from when the blog/fishing report is created. I will double check its working as expected.

**Comment by dolson334** [comment]
@bschmitz9 these should both be working.
