### ISSUE TITLE
Blog Posted On Date

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#217]
@dolson334  Right now I see all the Blog Date Posted On Dates as March 23, 2019. But I didn't create them today. How is that date being set? Want to make sure that blog dates aren't getting updated when I update a blog. Date should be set when I create a new blog and never change again.

**Comment by dolson334** [comment]
Did u create a new database today?

**Comment by bschmitz9** [comment]
@dolson334 yes. But fishing report dates still show in the past

**Comment by dolson334** [comment]
@bschmitz9 thats weird. My blog and fishing dates both show as today when I create my database today.
