### ISSUE TITLE
Story remaingPendingChanges

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#220]
Recreating:

1. Update story details.
2. Update story intro. 
3. Approve the story details change only.

It redirects back to the admin and updates the intro as well.

**Comment by bschmitz9** [comment]
@dolson334 same thing if you approve the intro. All pending changes get updated

**Comment by dolson334** [comment]
@bschmitz9 your second comment here is because the javascript was passing back "all" as the Id. I fixed.
