### ISSUE TITLE
Admin Home Page Picture Id

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#222]
Recreation:
1. Go to the admin home page.
2. Edit the main picture.
3. I have a console.log(header.action.modified);. This coming back as the picture below. The Id value within the "picture" shows a value of 1. This should instead be the 23 that is outside picture json. 23 is the correct value, we just need picture.id to equal 23. 
<img width="339" alt="pictureJson" src="https://user-images.githubusercontent.com/16144247/54893593-82e1da80-4e84-11e9-8590-8d12ae1065b8.png">

**Comment by dolson334** [comment]
@bschmitz9 when you are done with this assign it back to me as I will need to make a tweak on the backend.

**Comment by bschmitz9** [comment]
@dolson334 ok pull
