### ISSUE TITLE
Resort Photos remainingPendingChanges

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#226]
Recreation:

1. Update one photo or intro - seeing the same for both.
2. Go to preview and approve update
3. Page reloads to the preview when there are no more pending changes.

Reason: remaingPendingChanges is coming back as true. Should be false. 

If I go back to the admin I still see the "View and Approve Changes" button as well.

**Comment by dolson334** [comment]
@bschmitz9 I cant recreate this.

**Comment by bschmitz9** [comment]
@dolson334 looks to be working now.
