### ISSUE TITLE
Units and Boats Main Photo

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#232]
If the user adds two new photos and checks them both to be main they both get the isMain property. There should only ever be one. Recreation:

1. Edit a unit and make it the main photo.
2. Add another photo and make that one the main photo. 
3. Save.
4. Approve the update.
5. Go back to admin and open up the edit modal for that unit and view photos.

They both come back as the main photo. Take the last photo they make the main photo and make that the main photo.

Also, if the user deletes the main photo but has other main photos pending. Can you reset the new main photo to have "isMain" property set to true. I need that to set the "Main Photo" notification.

**Comment by dolson334** [comment]
@bschmitz9 For this one I think we should handle this in the modal, or somewhere in javascript. Basically, if 2 new photos are added and set as isMain only set isMain for the last one they selected. 

When the check box is checked you could fire an event that sets IsMain to false for all new photos except for the one your on. Thoughts?

**Comment by bschmitz9** [comment]
@dolson334 I can look into setting only one on the frontend but you'll still need to update the isMain property on the backend for whatever photo comes back to the server as the main so I can use that when the page re-loads.

**Comment by bschmitz9** [comment]
@dolson334 right now we're only passing back the newly added pictures array "addedPhotos" when the user saves. I'm not going to change that. But now there will only ever be one isMain photo in that "addedPhotos" array. And it should always be the last one in the array. So just check the addedPhotos and if one is set to isMain then that's your main photo and set all the others to false.

**Comment by dolson334** [comment]
@bschmitz9 yes this appears to be working as I would expect.
