### ISSUE TITLE
Deleting Home Page Slogan

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#244]
If the user deletes the slogan completely it should update right away and not trigger the preview changes button.

Do the same thing here as you did for the social media links.

**Comment by dolson334** [comment]
@bschmitz9 should we just have this update right away not matter what they change it to?

**Comment by bschmitz9** [comment]
@dolson334 I don't care. But we need to make sure its not too confusing on what is being updated right away and what isn't.

**Comment by dolson334** [comment]
@bschmitz9 This should be working now.
