### ISSUE TITLE
AboutUs Employees

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#247]
@bschmitz9 When editing an employee instead of returning the edited text from the edit modal like this
`{"name":"ccccc","details":"c","title":"ccc"}`

Can u instead return the actual pageText keys? For example, instead of name you would have aboutUsEmployee1Name.

**Comment by bschmitz9** [comment]
@dolson334 The edit modal should be returning only the modified inputs just like we have on all the other pages. That doesn't work here?

**Comment by dolson334** [comment]
@bschmitz9 it is, but these are page texts. So Ill need the key (aboutUsEmployee1Name). Is that doable? Otherwise I can create a new Employee object.

**Comment by bschmitz9** [comment]
@dolson334 Yea I think just create that object then.

**Comment by dolson334** [comment]
@bschmitz9 Ok now there is a list of employees.

Can you:
1. hook up the employee edit modal to take the correct value (name, title, and details)
2. include the employee id in the json that is returned from the edit modal. 
3. Make sure the picture Id is also returned.
