### ISSUE TITLE
About Us Preview Can be Set Up

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#253]
You should be able to set up the preview for section intros, employees, features.

**Comment by bschmitz9** [comment]
@dolson334 you should also be able to update and set up the preview for the video and the features intro pictures (3 stacked pics).

**Comment by dolson334** [comment]
@bschmitz9 

Intros are done. Working on employees now.

**Comment by bschmitz9** [comment]
@dolson334 functionality for approving an employee update can be completed now. Styling should be done for employees.
