### ISSUE TITLE
AboutUs FeaturesDetailed Intro 

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#255]
The very last intro needs to be aboutUsFeaturesDetailedIntroHeader and aboutUsFeaturesDetailedIntroHeader.

**Comment by bschmitz9** [comment]
@dolson334 those are the exact same thing

**Comment by bschmitz9** [comment]
@dolson334 the header and intro paragraph here aren't getting updated to pending when going to the preview page. Both isStaged remain false. I'm using aboutUsFeaturesDetailedIntroHeader for the header and aboutUsFeaturesDetailedIntroParagraph for the intro paragraph

**Comment by bschmitz9** [comment]
@dolson334  closing this but need this issue corrected - #250
