### ISSUE TITLE
AboutUs FeaturesIntro 1 vs 2

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#259]
I dont have a way of knowing whether the first or section feature was edited. Can you pass back the Id of the page text?

This is what I am seeing
`
{title: "lll", details: "Lorem, ipsum dolor si...}`

**Comment by bschmitz9** [comment]
@dolson334 use the id I put there. 1 is the first section feature, 2 is the second section feature.

**Comment by dolson334** [comment]
@bschmitz9 ok
