### ISSUE TITLE
After I add a picture they disapear on Admin

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#260]
For about us admin featuresIntro when I add a picture the page looks like this.

<img width="534" alt="noPics" src="https://user-images.githubusercontent.com/16144247/56457891-b827fe00-6346-11e9-8b4b-3f5b22cde8d9.png">

**Comment by bschmitz9** [comment]
@dolson334 try this again and let me know. Hard for me to test. Right now I am just showing the "Add Pictures' button if there isn't a first picture saved yet:

`<div *ngIf="!aboutUsFeatureIntroPictures.picture1.dir"
							class="col-sm-6 text-center feature-intro-pics-container admin-edit-hover">
							<p class="default-font-size">Give your visitors a look at what makes your resort so special.
								Add 3 of
								your favorite pictures here.</p>
							<button class="btn btn-primary cursor-pointer default-font-size pt-2 px-4"
								aria-hidden="true" title="Add your resort photos here"
								(click)="showModal('editFeaturesIntroPics')">Add Pictures</button>
						</div>`

Should that work?
