### ISSUE TITLE
AboutUs Edit Video

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#261]
When I edit the about us video the edit json comes back as this. 
`
{id: 4, key: "aboutUs.video.mp4", mp4Dir: "data:video/mp4;base64,AAAAIGZ0....."}`

The mp4Dir should be base64.

**Comment by bschmitz9** [comment]
@dolson334 ok I updated the property from mp4dir to base64. You just need the property name changed? If so, close this one.

**Comment by dolson334** [comment]
@bschmitz9 correct. working now.
