### ISSUE TITLE
Enpoint breaks when trying to update header and details of features row

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#265]

**Comment by dolson334** [comment]
@bschmitz9 this is because I dont know which feature is being edited (no id). you can give me the feature number (which is 1,2, 3, 4) or the actual pageText id (each pageText has a specific if from the database. You could see the getPageText function in utilities.. the text.id property).

**Comment by bschmitz9** [comment]
@dolson334 going to close this then and see if it is gone when I'm done updating About Us
