### ISSUE TITLE
keep getting 400 endpoint error on about us after saving a couple times

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#280]
The endpoint breaks after 4 or 5 saves, causing me to have to close everything down and rebuild every time.

**Comment by dolson334** [comment]
@bschmitz9 please post the error. Also, try a full clean or even a reclone.

**Comment by bschmitz9** [comment]
@dolson334 here is what I see in the console when the page reloads:

POST http://localhost:8080/resortPlatform/endpoint/getstories 400

**Comment by dolson334** [comment]
@bschmitz9 can u try a hard clean and rebuild?

**Comment by bschmitz9** [comment]
@dolson334 i'll try it later and reopen if there is still an issue
