### ISSUE TITLE
AboutUs Stage Page Need to Know section

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#283]
I want to just use the approveAboutUpdate() function in the main site controller for every approval. Can you pass in the section that is being updated, or set some variable on the controller so I know. So something that would say "employee" if were approving the employees.

Maybe there is something currently I can use?

**Comment by bschmitz9** [comment]
@dolson334 I added a section property to each object on page load. You can use that. For the employees, do it on the backend, so for each employee object just add a "section" property that says "employee". Then when that employee gets updated the approveAboutUpdate() function will have that information.

Section intro updates will have the same "section" property but those will run through the updateSectionIntroduction() function. Let's keep that. You just call the same endpoint on the backend.
