### ISSUE TITLE
updating photo doesn't remove it from stagedValues.dir

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#284]
Update a photo in the feature details section (last section) and when the page reloads the stagedValue.dir is still there.

**Comment by bschmitz9** [comment]
@dolson334 this applies to the features row as well. I'd check this in all sections.

**Comment by dolson334** [comment]
@bschmitz9 I assume you mean approving the picture?

**Comment by bschmitz9** [comment]
@dolson334 yes, approving the picture in the preview site doesn't remove the stagedValue

**Comment by dolson334** [comment]
@bschmitz9 I think your passing back the rough picture from the modal on the edit. If I approve the third picture.. you are passing back the first.

**Comment by bschmitz9** [comment]
@dolson334 where are you seeing that? I just went through and edited all of the pictures in the features row and the details section in the admin site and it looks like all pictures are being passed back correctly. And it looks like the preview page is showing the right picture with the right feature update. 

Give me a specific example and I'll take a look.

**Comment by dolson334** [comment]
@bschmitz9 

Recreation:
1. Update the 3rd picture in this section (aboutUsPopupFeature3).
2. Go to the main site and this is what youll see. 

![image](https://user-images.githubusercontent.com/16144247/57001663-979a4800-6b7f-11e9-9e74-d73c852923f4.png)

3. Approve this picture.
4. In the "approveAboutUpdate()" function in the mainsite/about controller this is the value passed for "this.updates". 

![image](https://user-images.githubusercontent.com/16144247/57001749-07a8ce00-6b80-11e9-9799-15b548122ad9.png)

5. This key should be "aboutUsPopupFeature3" and the id should be 13.

**Comment by dolson334** [comment]
@bschmitz9 I am still seeing this as broken.
