### ISSUE TITLE
Updating story picture doesn't add to stagedValues

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#289]
If I update one of the story pictures the picture doesn't get added to the stagedValues for that story.

**Comment by dolson334** [comment]
@bschmitz9 I assume you mean on the storied page. If so I cant recreate this.


<img width="657" alt="picForBrian" src="https://user-images.githubusercontent.com/16144247/57001369-f3fc6800-6b7d-11e9-80c6-35b157d4080d.png">
