### ISSUE TITLE
Blogs picture stagedValues empty

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#296]
Add picture to a  blog that doesn't previously have a picture, and then go to preview, the pictures array is empty causing page to break.

**Comment by dolson334** [comment]
@bschmitz9 I cant recreate this. The new picture shows up for me but it is not red.

**Comment by bschmitz9** [comment]
@dolson334 that's because there is no dir property in the picture's stagedValues. We're not using the stagedValues to show the new picture but I need it to show the red border. I'm checking for that to add the red border. There is a dir property anytime I update an existing picture, it's just not there when I add a picture to an existing blog for the first time.

**Comment by dolson334** [comment]
@bschmitz9 thats because the picture is new. So isNew is true. Can you use that instead?
