### ISSUE TITLE
Make the database better

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#311]
Put feature rows in an array like employees. Each object should have only what it needs. - stories and blogs don't need a video array. 

We shouldn't have to get the data again with getPageObject after the data comes from the database. It should already be ready to use like it is with employees.

**Comment by dolson334** [comment]
@bschmitz9 started on this tonight. Should be done tomorrow.

**Comment by dolson334** [comment]
@bschmitz9 I added 2 new features lists in aboutUs. Look at the getAboutData. They are just like employee now. Once you get this working assign this back to me and I will remove those page Texts. 

```
	this.featuresIntro = response.featuresIntro;
	this.featuresRow = response.featuresRow;
```

**Comment by dolson334** [comment]
@bschmitz9 a far as the extra properties on objects that dont need them (like videos on blogs) that is not as critical. I will write up tech debt item to make this changes.

**Comment by bschmitz9** [comment]
@dolson334  Started on featuresRow….I see 4 objects with a featuresIntro object name of "FeatureIntro1" if I make an update to name or details or photo I don't see any stagedValues to show as pending.

**Comment by bschmitz9** [comment]
@dolson334 for the featuresIntro I need 3 objects -> one with a title and intro, another with a title and intro, and then an object holding 3 pictures - which are the 3 pictures that overlap eachother. So it can look something like this:

`{
    title: "Intro 1",
    intro: "This is the intro for the first feature."
},
{
   title: "Intro 2",
   intro: "This is the intro for the second feature."
},
{
  picture1: "image1.png",
  picture2: "image2.png",
  picture3: "image3.png
}
`
then I can access it right off of the response like: this.featureIntros = response.featuresIntro;

**Comment by dolson334** [comment]
@bschmitz9 does it have to be "intro" and "title"? What about "name" and "details"?

**Comment by bschmitz9** [comment]
@dolson334 you can. I'll have to re-do the edit modal for about-us probably.

**Comment by dolson334** [comment]
@bschmitz9 they will use title and summary instead. changing that now.

**Comment by bschmitz9** [comment]
@dolson334 do title and details.

**Comment by bschmitz9** [comment]
@dolson334 make it title and details.

**Comment by dolson334** [comment]
@bschmitz9 yea

**Comment by dolson334** [comment]
@bschmitz9 you can work on the editmodal for admin site for featuresIntro now

**Comment by dolson334** [comment]
@bschmitz9 Ill let u hook the html up on the main site.Just like the admin site use the new feature objects.

**Comment by bschmitz9** [comment]
I'm closing this one. We can use the other ticket.
