### ISSUE TITLE
Put slogan property directly on the resort

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#313]
Can you put the slogan property directly on the resort object instead of within page texts. I want to get rid of that function completely.

**Comment by dolson334** [comment]
@bschmitz9 look for this.slogan and this.slogan2

**Comment by bschmitz9** [comment]
@dolson334 this still requires you to call a filter function to get the actual value. Same as calling pageText. For the sake of getting this done its fine but shouldn't need to call anything else once the response comes back. But I don't see the pending slogan getting put into stagedValues. I'm not sure what slogan2 is

**Comment by dolson334** [comment]
@bschmitz9 the slogan should be ready to go now. You will need to hook up the edit modals and the pending page html. But the staging should work now. 

As for the filter function, we need to create an object, like Feature that can hold a bunch of new text and picture options. We dot want to hard code things like slogan, etc.

**Comment by bschmitz9** [comment]
@dolson334 test the slogan and see if its set up correctly. I'm just passing back the slogan, logo, and photo objects when approving all. But when I try to update I'm getting a 500 error
