### ISSUE TITLE
Approved resort or fishing photo breaks endpoint

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#315]
Update resort or fishing photo only. Approve change. Endpoint breaks - 500 error.

**Comment by dolson334** [comment]
@bschmitz9 I need the actual picture object in the push . Right now you are putting the png uri in the array. 

![image](https://user-images.githubusercontent.com/16144247/58925323-b35bb580-870c-11e9-9ca2-c0b41ee11810.png)
