### ISSUE TITLE
AdminSite FeaturesRow 

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#316]
@bschmitz9 the features row should be populating correctly on the admin site now. You will need to fix the edit modal so that the fields populate correctly (I can rename things if I need to).

**Comment by bschmitz9** [comment]
@dolson334 I updated the featuresRow to be the same as the employees edit. If you can set up the featuresRow and the video to save then I can work on the preview page some more if needed. I'll set up the featuresIntro the same way next.

**Comment by dolson334** [comment]
@bschmitz9  When updating a feature you are returning this json. 

```
{
  "details": "some great details 2qqq",
  "id": 6,
  "title": "featuresIntro2qqq"
}
```

I need it to look like this. 

```
{
  "feature": {
    "details": "some great details 2qqq",
    "id": 6,
    "title": "featuresIntro2qqq"
  }
}
```

**Comment by dolson334** [comment]
@bschmitz9 the featuresRow and video should be updating correctly now. You can hook up the featureIntro the same way. Eventually I would like to change all update calls on all pages to using just the "updates" main object from the modal instead of "updates.action.modified". It makes my back end way way reusable. 

```

		this.aboutAdminService.update(this.token, updates).subscribe(response => {
			if (this.previewActive) {
				this.loadingMessage = "Adding
```

**Comment by bschmitz9** [comment]
@dolson334 you can use anything you need in that "update" object. So if you want to pass the full updates object back go for it. It doesn't matter to me. I'm just giving you the data you need. So if you want to do this you can:

`aboutAdminService.update(token, {feature: updates}).subscribe...`

I just need the data back the same way for the preview site as it is now.

And intro page texts is already set up the same way as employees, featureIntro, and featuresRow.
