### ISSUE TITLE
FeaturesRow main site showing weird

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#318]
Is this how this is supposed to look? Employees look different.

![image](https://user-images.githubusercontent.com/16144247/59893210-d4c1d000-93a1-11e9-9a7c-0123ba198b9f.png)

**Comment by bschmitz9** [comment]
@dolson334 no I fixed that. But when I try to approve the updates I get a 500 server error.

**Comment by bschmitz9** [comment]
@dolson334 no I fixed that.
