### ISSUE TITLE
AboutUs Picture Not Updating

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#326]
@bschmitz9 

1. update features intro picture.
2. The picture updates correctly in the database. 
3. The picture does not show correctly in the staging site.

**Comment by bschmitz9** [comment]
@dolson334 staged values isn't getting cleared out after updated. That should be empty when the page reloads after approving the update. If there is a stagedValue there it's going to take that.

**Comment by dolson334** [comment]
@bschmitz9 you have to look at the pictures[0] stageValues like employees.

**Comment by bschmitz9** [comment]
@dolson334 I am looking at that:

`<img *ngIf="!feature.pictures[0].stagedValues.dir || page !== 'pending'"
							class="feature-box__photo" src="{{feature.pictures[0].dir}}" alt="Feature Image 1"
							aria-describedby="feature1-heading">
						<img *ngIf="feature.pictures[0].stagedValues.dir && page === 'pending'"
							src="{{feature.pictures[0].stagedValues.dir}}" class="feature-box__photo"
							alt="Feature Image 1" aria-describedby="feature1-heading"
							[ngClass]="{'isStaged': feature.pictures[0].stagedValues.dir && page === 'pending'}">`

**Comment by davidOlsonSpfcu** [comment]
@bschmitz9 Update the last featuresIntro feature picture. Look at the console.log I added in the getAboutUs call. You can see that the stagedValues.dir value is set to the new picture.
