### ISSUE TITLE
Need resort name when logging into admin site

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#340]
How can I get the name of the resort when they login? I need to add the resort name or owner name in the top navigation where it says "Welcome" so that it says "Welcome, MooseLake". Or whatever name you think it makes most sense to go by.

**Comment by dolson334** [comment]
@bschmitz9 I added it to the response. Login and see the alert I added.

**Comment by bschmitz9** [comment]
@dolson334 sorry I need this in the navigation component when it loads. That is where the Welcome line is coming from. So it'll be present on every admin page.

Folder path -> webcontent/adminSite/reusable/navigation

I put a call inside the ngOnInit function called getResortName. You can adjust it as needed.

**Comment by dolson334** [comment]
@bschmitz9 did you push? Iam not seeing the getResortName function.

**Comment by bschmitz9** [comment]
@dolson334 pull now and you should see it.

**Comment by bschmitz9** [comment]
@dolson334 I don't see it. Response is empty.

**Comment by dolson334** [comment]
@bschmitz9 no need for new endpoint call. Pull and see new alert.
