### ISSUE TITLE
ContactUs Intro JSON is Wrong

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#341]
@bschmitz9 modified is duplicated. 

```
{
  "modified": [
    {
      "id": 42,
      "text": "1"
    },
    {
      "id": 40,
      "text": "2"
    },
    {
      "id": 42,
      "text": "1"
    },
    {
      "id": 40,
      "text": "2"
    },
    {
      "id": 42,
      "text": "1"
    },
    {
      "id": 40,
      "text": "2"
    },
    {
      "id": 42,
      "text": "1"
    },
    {
      "id": 40,
      "text": "2"
    }
  ],
  "type": "save-existing",
  "selected": [
    {
      "isVideoStaged": false,
      "log": "java.util.logging.Logger@6d74e172",
      "isPictureStaged": false,
      "isStaged": false,
      "videos": [],
      "isNew": false,
      "objectType": "PAGE_TEXT",
      "features": [],
      "stagedValues": {},
      "id": 42,
      "objectMetaType": "resort",
      "text": "Contact Us Page Header",
      "key": "contactUsPageHeader"
    },
    {
      "isVideoStaged": false,
      "log": "java.util.logging.Logger@6d74e172",
      "isPictureStaged": false,
      "isStaged": false,
      "videos": [],
      "isNew": false,
      "objectType": "PAGE_TEXT",
      "features": [],
      "stagedValues": {},
      "id": 40,
      "objectMetaType": "resort",
      "text": "Contact Us Intro Paragraph",
      "key": "contactUsIntroParagraph"
    }
  ]
}
```

**Comment by bschmitz9** [comment]
@dolson334 where are you seeing this? I don't see that. Here is what I see inside of the admin contact-us.service.ts file. This is right before it gets sent to the endpoint /upsertcontactinfo.

`{token: "eyJraWQiOiJtb29zZUxha2UiLCJ0eXAiOiJKV1QiLCJhbGciOi…AxNH0.CS3fKAcvDOVk19AhPwO0jm5iQfkIcJZKq8rAJEb7N8c", updates: {…}}
token: "eyJraWQiOiJtb29zZUxha2UiLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkb2xzb24zMzRAZ21haWwuY29tc3VjY2VzczIzNDkwOjA6MDowOjA6MDowOjEiLCJleHAiOjE1NjM0MzUwMTQsImlhdCI6MTU2MzQzMjAxNH0.CS3fKAcvDOVk19AhPwO0jm5iQfkIcJZKq8rAJEb7N8c"
updates:
   modified: Array(2)
      0: {id: 42, text: "Contact Us Page Header aa"}
      1: {id: 40, text: "Contact Us Intro Paragraph aaa"}
       length: 2
   selected: Array(2)
      0: {isVideoStaged: false, log: "java.util.logging.Logger@37edf947", isPictureStaged: false, isStaged: false, videos: Array(0), …}
      1: {isVideoStaged: false, log: "java.util.logging.Logger@37edf947", isPictureStaged: false, isStaged: false, videos: Array(0), …}
       length: 2
  type: "save-existing"

**Comment by bschmitz9** [comment]
@dolson334 where are you seeing this? I don't see that. Here is what I see inside of the admin contact-us.service.ts file. This is right before it gets sent to the endpoint /upsertcontactinfo.
```
token: "eyJraWQiOiJtb29zZUxha2UiLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkb2xzb24zMzRAZ21haWwuY29tc3VjY2VzczIzNDkwOjA6MDowOjA6MDowOjEiLCJleHAiOjE1NjM0MzUwMTQsImlhdCI6MTU2MzQzMjAxNH0.CS3fKAcvDOVk19AhPwO0jm5iQfkIcJZKq8rAJEb7N8c"
updates:
   modified: Array(2)
            0: {id: 42, text: "Contact Us Page Header aa"}
            1: {id: 40, text: "Contact Us Intro Paragraph aaa"}
     selected: Array(2)
            0: {isVideoStaged: false, log: "java.util.logging.Logger@37edf947", isPictureStaged: false, isStaged: false, videos: Array(0), …}
            1: {isVideoStaged: false, log: "java.util.logging.Logger@37edf947", isPictureStaged: false, isStaged: false, videos: Array(0), …}
    type: "save-existing"
```
Don't know how the text would have "1" or "2" next to it. The admin page breaks when I try to update the intro contact us so if its in the main site I can't see it.

**Comment by dolson334** [comment]
@bschmitz9 This was actually a back end bug. I fixed. However, when I click update the modal does not go away. Do you get that?

**Comment by bschmitz9** [comment]
@dolson334 yea I fixed the modal. Closing this then.
