### ISSUE TITLE
Fishing Photos update intro breaks

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#345]
1. Add a new photo
2. Update intro
3. Decline the photo change in preview site. 
4. Approve the intro.

End point breaks - 500 error. Only when declining a new photo.

**Comment by bschmitz9** [comment]
@dolson334 same with declining the intro if you follow the above steps.

**Comment by dolson334** [comment]
@bschmitz9  I cant recreate this

**Comment by bschmitz9** [comment]
@dolson334 Not sure then. It doesn't work for me. Make sure you're adding a new photo and not editing an already existing one.

**Comment by dolson334** [comment]
@bschmitz9 this is what is being passed back with this recreation. 

[
  {
    "storyId": "0",
    "FISHING_PICS_CACHE_NAME": "fishingPictures",
    "log": "java.util.logging.Logger@77e7cb8a",
    "isPictureStaged": false,
    "objectTypeName": "fishing",
    "isStaged": false,
    "videos": [],
    "PICTURE_WRITE_DIR": "c:/bantor/pictures",
    "PICTURE_URL_DIR": "http://localhost:8080/pictures",
    "dir": "http://localhost:8080/pictures/fishing/1564019011217.png",
    "objectType": "PICTURE",
    "features": [],
    "BASE64_PNG_STARTER": "data:image/png;base64,",
    "unitId": "0",
    "details": "w",
    "id": 107,
    "RESORT_PICS_CACHE_NAME": "resortPictures",
    "key": "null",
    "featureId": "0",
    "isVideoStaged": false,
    "$SWITCH_TABLE$objects$Picture$PICTURE_TYPE": "null",
    "base64String": "null",
    "BASE64_JPEG_STARTER": "data:image/jpeg;base64,",
    "isMain": "false",
    "resortId": "0",
    "byteArray": "null",
    "employeeId": "0",
    "isNew": true,
    "fishingReportId": "0",
    "stagedValues": {},
    "pictureType": "null",
    "blogId": "0",
    "boatId": "0"
  },
  {
    "isVideoStaged": false,
    "log": "java.util.logging.Logger@2551402e",
    "isPictureStaged": false,
    "isStaged": true,
    "videos": [],
    "isNew": false,
    "objectType": "PAGE_TEXT",
    "features": [],
    "stagedValues": {
      "text": "111"
    },
    "id": 47,
    "objectMetaType": "resort",
    "text": "Fishing Pictures Page Header",
    "key": "fishingPicturesPageHeader"
  },
  {
    "isVideoStaged": false,
    "log": "java.util.logging.Logger@2551402e",
    "isPictureStaged": false,
    "isStaged": true,
    "videos": [],
    "isNew": false,
    "objectType": "PAGE_TEXT",
    "features": [],
    "stagedValues": {
      "text": "222"
    },
    "id": 46,
    "objectMetaType": "resort",
    "text": "Fishing Pictures Intro Paragraph",
    "key": "fishingPicturesIntroParagraph"
  }
]

it needs to be this,

```
[
  {
    "isVideoStaged": false,
    "log": "java.util.logging.Logger@1ebee09d",
    "isPictureStaged": false,
    "isStaged": true,
    "videos": [],
    "isNew": false,
    "objectType": "PAGE_TEXT",
    "features": [],
    "stagedValues": {
      "text": "new header"
    },
    "id": 47,
    "objectMetaType": "resort",
    "text": "Fishing Pictures Page Header",
    "key": "fishingPicturesPageHeader"
  },
  {
    "isVideoStaged": false,
    "log": "java.util.logging.Logger@1ebee09d",
    "isPictureStaged": false,
    "isStaged": true,
    "videos": [],
    "isNew": false,
    "objectType": "PAGE_TEXT",
    "features": [],
    "stagedValues": {
      "text": "new summary"
    },
    "id": 46,
    "objectMetaType": "resort",
    "text": "Fishing Pictures Intro Paragraph",
    "key": "fishingPicturesIntroParagraph"
  }
]
```
