### ISSUE TITLE
Updating Existing Blog to have a photo breaks endpoint

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#346]
Add a photo to an existing Blog that did not have one when initially created. End point breaks - 500 error.

**Comment by dolson334** [comment]
@bschmitz9 similar to when you add a new photo to a unit can you put this new photo in modified as "addedPhotos"?

**Comment by bschmitz9** [comment]
@dolson334 I can but this won't solve the issue this ticket is talking about. This is for an existing blog you are editing. So you are going through the edit modal (not like adding a new picture to a new blog).  

All the adding new stuff looks to be working fine so I think we should just leave it.
