### ISSUE TITLE
Updating units intro issues

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#350]
Updating the intro summary doesn't show in the preview page. 
Approving any intro change in the preview doesn't do anything when you get back to the admin site. Preview button is still there and the text isn't updated.

**Comment by dolson334** [comment]
@bschmitz9 this is what is passed back when the heading and summary are edited. Looks like only the header is in the modified array. 

```
{
  "modified": [
    {
      "id": 64,
      "text": "Header adjusted text"
    }
  ],
  "type": "save-existing",
  "selected": {
    "isVideoStaged": false,
    "log": "java.util.logging.Logger@41003c9a",
    "isPictureStaged": false,
    "isStaged": true,
    "videos": [],
    "isNew": false,
    "objectType": "PAGE_TEXT",
    "features": [],
    "stagedValues": {
      "text": "1"
    },
    "id": 64,
    "objectMetaType": "resort",
    "text": "Units Page Header",
    "key": "unitPageHeader"
  }
}
```

**Comment by dolson334** [comment]
@bschmitz9 this is not fixed. Same object is passed back with only the header.
