### ISSUE TITLE
Deleting unit video breaks endpoint

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#353]
Deleting a unit video and saving breaks endpoint - 500.

**Comment by dolson334** [comment]
@bschmitz9 this is what is passed back when deleting a video. This should be like any other delete where the modified just has the objectType (so video) and id. 

```
{
  "modified": {
    "deleteSavedVideo": true,
    "deleteOnly": true
  },
  "type": "deleting",
  "selected": {
    "isVideoStaged": false,
    "sleeps": "5",
    "log": "java.util.logging.Logger@12520b34",
    "isPictureStaged": false,
    "isStaged": false,
    "videos": [
      {
        "VIDEO_MP4_STARTER": "data:video/mp4;base64,",
        "isVideoStaged": false,
        "log": "java.util.logging.Logger@3d124087",
        "mp4ByteArray": "null",
        "isPictureStaged": false,
        "VIDEO_URL_DIR": "http://localhost:8080/videos",
        "objectTypeName": "unit",
        "isStaged": false,
        "videos": [],
        "isNew": false,
        "dir": "null",
...
...
...
```

**Comment by bschmitz9** [comment]
@dolson334 you should have what you need to delete the video. Each unit can only have one video and you get the selected unit. Just delete the video from that unit.

**Comment by bschmitz9** [comment]
@dolson334 I added the modified video. So if it has "deletedVideo" then you just delete that video. If there is a "newVideo" then you add that video. If both are present then delete the saved video and add the new video.
