### ISSUE TITLE
Adding New Unit doesn't update areUnitsStaged

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#355]
areUnitsStaged remains false when a new Unit is added so no preview is available.

**Comment by dolson334** [comment]
@bschmitz9 pull and take a look to make sure this is right.

**Comment by bschmitz9** [comment]
@dolson334 yea this looks better. Only issues I see is if you add a video while creating the new unit there is no video in the videos array when I get to the unit page.

**Comment by dolson334** [comment]
@bschmitz9 your passing back the url. Can you pass back the base64?

```
{"item":{"bedrooms":"2","sleeps":"4","baths":"3","price":"2","name":"ss","details":"r","video":{"mp4":"blob:http://localhost:4200/35cde9e2-4600-45be-988a-8c096db54acd"}
...
...
...

```

**Comment by bschmitz9** [comment]
@dolson334 alright this should be good. Try adding and deleting a video. Check to make sure you can save a new unit and then update the units as well.

**Comment by dolson334** [comment]
@bschmitz9 to be consistent with pictures can you say "addedVideo" instead of "newVideo" in the modified? Before you had it as just "video". 

i have the backend just looking for "newVideo" for now and its working. But when you change it to "addedVideo" ill switch it.

**Comment by bschmitz9** [comment]
@dolson334  k. same for about us and unit video

**Comment by dolson334** [comment]
@bschmitz9 did you push? it still says newVideo?

**Comment by bschmitz9** [comment]
@dolson334 pull now

**Comment by dolson334** [comment]
@bschmitz9 ok working now
