### ISSUE TITLE
Contact Us Social Media Links

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#358]
I updated these to use the pageText Objects now like everything else. So you'll have to update on your end. Not instead of the just the text I'm passing back the text object into the modified. Selected is just the resort info regardless of weather you update address info or social media links. We're not adding social media links to pending anyway so I'm thinking that should work.

**Comment by dolson334** [comment]
@bschmitz9 these values are pageTexts. The selected that is passed back here is the RESORT. These should be coming back like the intro and header.

**Comment by bschmitz9** [comment]
@dolson334 ok I got your pageTexts in there for ya now buddy. Make sure to account for the case where they are adding a social media link into the database for the first time.

**Comment by dolson334** [comment]
@bschmitz9 This is what is passed back when you update one social media link.

 When you pass back modified as a JSONObject can you also pass back the selected as a JSONObject (right now its a JSONArray). And when modified is JSONArray selected should also be a JSONArray. 

```
{
  "modified": {
    "contactUsFacebookLink": {
      "isVideoStaged": false,
      "log": "java.util.logging.Logger@2a920235",
      "isPictureStaged": false,
      "isStaged": false,
      "videos": [],
      "isNew": false,
      "objectType": "PAGE_TEXT",
      "features": [],
      "stagedValues": {},
      "id": 38,
      "objectMetaType": "resort",
      "text": "https://www.facebook.comq",
      "key": "contactUsFacebookLink"
    }
  },
  "type": "save-existing",
  "selected": [
    {
      "isVideoStaged": false,
      "log": "java.util.logging.Logger@2a920235",
      "isPictureStaged": false,
      "isStaged": false,
      "videos": [],
      "isNew": false,
      "objectType": "PAGE_TEXT",
      "features": [],
      "stagedValues": {},
      "id": 38,
      "objectMetaType": "resort",
      "text": "https://www.facebook.com",
      "key": "contactUsFacebookLink"
    }
  ]
}
```

**Comment by bschmitz9** [comment]
@dolson334 pull and try this. The contact info section of this page is way different from the others. The edit modal for this page is independent of the other edit modals. Try to make this work. You may have to write a little bit of code. For the modified just take what you need from the textObject - id and text are there.

**Comment by dolson334** [comment]
@bschmitz9 this is close. But currently I dont know what in the modified is being changed (in this case its text). When we update the intro I know just the "text" is being updated because thats all thats in there. So you can you just put the "text" in there?

```
{
  "modified": [
    {
      "isVideoStaged": false,
      "log": "java.util.logging.Logger@7690e420",
      "isPictureStaged": false,
      "isStaged": false,
      "videos": [],
      "isNew": false,
      "objectType": "PAGE_TEXT",
      "features": [],
      "stagedValues": {},
      "id": 38,
      "objectMetaType": "resort",
      "text": "https://www.facebook.com1",
      "key": "contactUsFacebookLink"
    }
  ],
  "type": "save-existing",
  "selected": [
    {
      "isVideoStaged": false,
      "log": "java.util.logging.Logger@7690e420",
      "isPictureStaged": false,
      "isStaged": false,
      "videos": [],
      "isNew": false,
      "objectType": "PAGE_TEXT",
      "features": [],
      "stagedValues": {},
      "id": 38,
      "objectMetaType": "resort",
      "text": "https://www.facebook.com",
      "key": "contactUsFacebookLink"
    }
  ]
}
```
