### ISSUE TITLE
Create Reservation Data Integrity Script

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#36]
1. Write a sql script that will return all reservations whose checkIn date is after the checkOut date (because this is bad right?). We need to know if we have bad data in the DB. 

2. Save the script to ...bantor\resortPlatform\resortPlatform\Data Integrity Scripts

**Comment by dolson55** [comment]
what table would the checkin and checkOut date be?

**Comment by dolson55** [comment]
Nevermind found it.

**Comment by dolson55** [comment]
Also there doesnt seem to be a Data Integrity Scripts folder.

**Comment by dolson334** [comment]
pull again

**Comment by dolson55** [comment]
Just pushed it up.  Take a look the code is pretty simple but I think I got it.

**Comment by dolson55** [comment]
Feel free to correct me if I'm wrong.  Haven't wrote SQL in awhile

**Comment by dolson334** [comment]
Thats is. one change. can you make return all columns?  Thx. good job
