### ISSUE TITLE
Home page needs to be setup

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#364]
I think you should have everything from me to set this page up, if not let me know.

**Comment by dolson334** [comment]
@bschmitz9 

When I update the logo the picture within the modified is missing the "id".

**Comment by dolson334** [comment]
@bschmitz9 When I update the backgroundimage .. there is no "selected".

**Comment by dolson334** [comment]
@bschmitz9 same issue when updating the background image.

**Comment by bschmitz9** [comment]
@dolson334 ok updated

**Comment by dolson334** [comment]
@bschmitz9 the logo works good. 

1. the slogan is a pageText. It should come back like other pageTexts. 
2. When editing just the background image there is no "selected".

**Comment by bschmitz9** [comment]
@dolson334 ok check it now. Retry everything to make sure they're still working - background image and logo.

**Comment by dolson334** [comment]
@bschmitz9 this looks good. can you make once change. Slogan is actually a "FEATURE" object. so its has "title" and "details". So when its edited instead of "text" can you pass back "details"?

**Comment by bschmitz9** [comment]
@dolson334 ok done

**Comment by dolson334** [comment]
@bschmitz9 Slogan only working now. 

But when I edit the background image and the slogan here is what is passed back. Should have "details" instead of text and base64 should be picture: { base64: "adfhaskldgfkasdf..."

```
[
  {
    "id": 1,
    "text": "cxcxx"
  },
  {
    "base64": "iVBORw0KGgoAAAA...."
  }
]
```

**Comment by bschmitz9** [comment]
@dolson334 ok done
