### ISSUE TITLE
Boat Capacity Errors when updated

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#365]

**Comment by bschmitz9** [comment]
@dolson334 are you just seeing this error? -> EditModalComponent.html:268 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'. 

This error comes when the edit modal pops up. I'll look into it later. Not related to capacity. 

But yea the endpoint does break when capacity is edited. I think this is on your end tho. The data being passed back looks correct to me.

**Comment by dolson334** [comment]
@bschmitz9 I fixed the capacity issue. 

I am seeing this issue you mentioned above. You may want to write up another bug for it or something.
