### ISSUE TITLE
Contact Info Preview Page

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#366]
Same issue for the following 2 cases:

1. In the admin update all 3 items - contact info, intro, and background image. 
2. In the admin update the contact info and the background image.

The page redirects back to the admin when the background image is the last to remain pending in the preview site. remainingPendingChanges comes back as false. I think the picture is getting updated with the other item because when I go back to the admin there is no pending picture anymore.

But this looks to work fine if you just have a pending header and background image.

**Comment by dolson334** [comment]
@bschmitz9 the issue here is that when you edit an address and the photo... the object (which is resort) that is passed back has the pictures and the text changes getting approved. 

We could: 
1. Make this page an approval all only page (like the home page)
2. Pass back some info stating what on the resort object is being unstaged. So if you just only approved address you could indicate that somehow. 

What you think?

**Comment by bschmitz9** [comment]
@dolson334 check the "key" property in the section object. If there is no key then you know its the resort object and the user is updating the contact information. If the key equals "contactUsBackground" then the user is updating just the background image. Intro has its own keys too.

**Comment by dolson334** [comment]
@bschmitz9 I dont see a key

**Comment by bschmitz9** [comment]
@dolson334 its in the selected picture object. You created it. "key"


Also, I'm not sure what you're talking about because when I approve the background image change in the preview site the only thing being passed back is the photo object. The resort object is only getting passed back when I approve the contact information at the bottom of the page.

**Comment by dolson334** [comment]
@bschmitz9 right but when you pass back the resort object the "contactUsBackGround" image picture is within the resort object so it is also unstaged. 

Can you do one of the following:
1. either just delete this picture when just the address is approved. 
2. just make this a approval all/delete all page

**Comment by bschmitz9** [comment]
@dolson334 ok so can't you just write some code so that when the resort object is passed back from the contact us preview page the contactUsBackground Image is not updated? Sounds like you have approve all functionality for a single item update. 

I'm not really sure what you mean by "delete this picture"..what are meaning?

I think this page should have indivdual approval. There can be alot of potential changes to only allow approve all / delete all.

**Comment by dolson334** [comment]
@bschmitz9 done.. test this a bit.. should be working now.
