### ISSUE TITLE
Resort Photos Update

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#368]
Update a resort photo and approve the change in the preview site. The page should redirect back to the admin but "remainingPendingChanges" is coming back as true so the page stays on the preview site with no more pending changes.

**Comment by dolson334** [comment]
@bschmitz9 I cant recreate this. Appears to be working perfectly for me.

**Comment by bschmitz9** [comment]
@dolson334 maybe it was something I did before but I'm not sure. Closing for now
