### ISSUE TITLE
About Us Video Issue

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#373]
@bschmitz9 when I edit the existing video the JSON passed back is acting like I am adding a new one. 
Currently the modified says "addedVideo"
`{"addedVideo":{"base64":"data:videojklashdfkjhasdfkahsdfkjha`

Instead, like when we edit a picture (below) the JSON should have the video id and say "video" with the base64. 
`{"id":1,"picture":{"base64":"iVBORw0KGgoAAAANSUhEUgA`

**Comment by bschmitz9** [comment]
@dolson334 this is what I see when I update the edit video. This is right before it hits the endpoint in the about.service.ts:

       `updates:
           modified:
                   video: base64: "data:video/mp4;base64,AAAAIGZ0eXBpc29tAAACAGlzb21p"
                   id: 4
                   key: "aboutUs.video.mp4"
            selected: {VIDEO_MP4_STARTER: "data:video/mp4;base64,", isVideoStaged: false, log: "java.util.logging.Logger@1b7c8440", mp4ByteArray: "null", isPictureStaged: false, …}
 `
