### ISSUE TITLE
Update text throughout site.

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#382]
As you get time go through each page and update the text so that it is legit and not dummy text. Pick text off of other resort websites and change it a little bit. Update through the admin site as a way of testing at the same time.

I will send you all the pictures as I get them for each page.

**Comment by bschmitz9** [comment]
When you do this make the text good and make sure you set some of the descriptions to the maximum amount of characters allowed. Only one that doesn't have a max length is the blog - that can be as long as they want

**Comment by dolson334** [comment]
@bschmitz9 I wont do this until the week before I go see ed. That way I wont have to rebuild database. We should be pretty stable by then.

**Comment by dolson334** [comment]
@bschmitz9 Ill be done with these tomorrow. Then you can review if youd like.

**Comment by bschmitz9** [comment]
@dolson334 are we fine to just take text from ed's website and use it on ours?

**Comment by bschmitz9** [comment]
@dolson334 I'm going to close this for now. I'll add text when taking the pictures from Ed's website.
