### ISSUE TITLE
CORS Errors

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#383]
Are you getting these errors? I cant really even access the site?

**Comment by bschmitz9** [comment]
@dolson334 no I'm not seeing any new CORS errors on my end

**Comment by dolson334** [comment]
@bschmitz9 damnit...I dont know what going on. really whooching me.

**Comment by bschmitz9** [comment]
@dolson334 what's the error?

**Comment by dolson334** [comment]
that cross origin error. Can you push what you have when your at a decent spot? And pull my latest
