### ISSUE TITLE
Adding a New Story without picture breaks endpoint.

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#384]

**Comment by dolson334** [comment]
@bschmitz9 ok this should work now. There is a js error when you add a story without a picture and then go to the staging site.

**Comment by bschmitz9** [comment]
@dolson334 I don't see a JS error.

**Comment by dolson334** [comment]
@bschmitz9 ok i dont see it with your latest push. Now though when you add a story with no picture there is no "approve" button.
