### ISSUE TITLE
Forgot Password Functionality

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#386]
Is this set up on your end?

**Comment by dolson334** [comment]
@bschmitz9 how so?

**Comment by dolson334** [comment]
@bschmitz9 right now we are storing the jwt (login) token i local storage. This persists even after you clse the browser (which is bad). SO if you login then close the browser, then open a new browser and go right to the units page the token is still saved in local storage. 

 Can you switch this to session storage?

**Comment by bschmitz9** [comment]
@dolson334 meaning if I click the link and type in my email, I get emailed either another password or there is a way for me to set a new password.. ya know, like any other website.

**Comment by dolson334** [comment]
@bschmitz9 yea, I suppose thats fine then. I think that is ho its working. I need to do some more testing here though. Feel free to do the same.

**Comment by dolson334** [comment]
@bschmitz9 And ill look at the forgot password func now.

**Comment by dolson334** [comment]
@bschmitz9 this is almost working. Just need to complete the update password call. Need you to setup the "updatepassword" call in js on the new-password.component. Will need the newPassword and the username.

**Comment by dolson334** [comment]
@bschmitz9 Also, I have to turn a security feature off on my google account for this. I turned it back on because otherwise it will gethacked. So dont worry about the email your supposed to get. Just update that endpoint call and we should be good.

**Comment by bschmitz9** [comment]
@dolson334 by username you mean email they use to sign in? How can I get that assuming they haven't actually been able to log in yet? I'm assuming we don't have access to the token either...

The functionality of this is they click Forgot Password put in there email and then get a link to the  new password page in the email right? That's what its looking like anyway.

**Comment by dolson334** [comment]
@bschmitz9 the email is the username.

**Comment by bschmitz9** [comment]
@dolson334 ok this should be ready for you to finish

**Comment by dolson334** [comment]
@bschmitz9 this is working. We will need to test again once we get a resorts email domain.
