### ISSUE TITLE
Add home link to main site navigation

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#387]
@bschmitz9 most resort sites have this and I think we should as well.

**Comment by bschmitz9** [comment]
@dolson334 there is nothing there for them on the home page. They would click a link to the home page and then have to click another link to go somewhere else. The home page is just buttons and links. If we add more things to the home page maybe it makes more sense. Modern websites these days  link back to the home page through the company name / logo on the left side of the nav - which is what we have now.
