### ISSUE TITLE
Too much description space

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#388]
@bschmitz9  Can you make the text box smaller on these pictures. 

<img width="290" alt="picture" src="https://user-images.githubusercontent.com/16144247/63068413-b5927b00-bed8-11e9-96c1-d081cce4fb19.png">

**Comment by dolson334** [comment]
@bschmitz9 will need to do this for all pictures on all pages.

**Comment by bschmitz9** [comment]
@dolson334 I just went through and updated all the heights. If we don't set a height in the css then each picture is going to be a completely different height across the row based on the amount of text it has, which looks like a mess. The heights right now are based on the maximum amount of characters we are allowing - so for the pictures, the max amount of characters is 215. If they used all 215 characters it would fill the space nicely. Pretty much all websites take items in a row and set them to the same height. It's harder with this as we don't know how much text they are going to put in but I'd imagine more then 4 words usually.

When you add text just make sure you have some pictures with a max description. And we can adjust as we see people using it moving forward. 

Eventually I can look into making the boxes as tall as the tallest one on the page but I'd have to look into that a little bit and there are more important things right now.

**Comment by bschmitz9** [comment]
@dolson334 I also need a fixed height to be able to set the pending changes location within each box.

**Comment by bschmitz9** [comment]
@dolson334 let's leave as it for now it'll look better when we add text. And then we'll see how resorts use it moving forward and adjust as needed
