### ISSUE TITLE
Create Sql Script To count number of reservations booked Today (today begin the current day)

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#39]
1. Use the "CREATED" column to determine when they were booked. 
2. put script in same data integrity directory.

**Comment by dolson55** [comment]
Check out what I pushed and give me feedback.

**Comment by dolson334** [comment]
Thats the right idea. However, getDate() and CREATED are both datetime. So they will have results down to the milisecond like 2017-03-08 15:14:15.667. So for your query to be true getdate() and CREATED would have to have the same exact timestamp (which is impossible). Think more about selecting where CREATED is between midnight last night and midnight tonight.

**Comment by dolson55** [comment]
Okay.  Could I try casting it?  Like this:

SELECT count(*)
FROM Reservation
WHERE Created = (cast(getdate() as date));

**Comment by dolson334** [comment]
You will need to cast Created as well I think

**Comment by dolson55** [comment]
I don't think you can cast Created.  I'm getting syntax errors

**Comment by dolson334** [comment]
Try 

`CREATED between 'timestamp1' and 'timestampe2'

But to get timestamp2 and timestamp2 you will need to use getdate() to auto derive midnight yesterday an dmidnight today. `

**Comment by dolson55** [comment]
Take a look at what I pushed.
