### ISSUE TITLE
Adding A New Logo 

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#392]
Delete the existing home page logo and then add a new one. Saving a new one doesn't trigger the "View and Approve Changes" button.

**Comment by dolson334** [comment]
This is what is passed back when a logo is deleted. The modified should have the logo id in it and the selected should be a JSON object not an json array. 
{
  "modified": [
    {},
    {}
  ],
  "type": "deleting",
  "selected": [
    null,
    {
      "storyId": "0",
      "FISHING_PICS_CACHE_NAME": "fishingPictures",
      "log": "java.util.logging.Logger@560278f5",
      "isPictureStaged": false,
      "objectTypeName": "resort",
      "isStaged": false,
      "videos": [],
      "PICTURE_WRITE_DIR": "c:/bantor/pictures",
      "PICTURE_URL_DIR": "http://localhost:8080/pictures",
      "dir": "http://localhost:8080/pictures/resort/1566265634097.png",
      "objectType": "PICTURE",
      "features": [],
      "BASE64_PNG_STARTER": "data:image/png;base64,",
      "unitId": "0",
      "details": "a resort picture description",
      "id": 20,
      "RESORT_PICS_CACHE_NAME": "resortPictures",
      "key": "logo",
      "featureId": "0",
      "isVideoStaged": false,
      "$SWITCH_TABLE$objects$Picture$PICTURE_TYPE": "null",
      "base64String": "null",
      "BASE64_JPEG_STARTER": "data:image/jpeg;base64,",
      "isMain": "false",
      "resortId": "0",
      "byteArray": "null",
      "employeeId": "0",
      "isNew": false,
      "fishingReportId": "0",
      "stagedValues": {},
      "pictureType": "null",
      "blogId": "0",
      "boatId": "0"
    }
  ]
}

**Comment by dolson334** [comment]
@bschmitz9 I am guessing the other items you wrote are related to this. If you fix I can work on tomorrow AM.

**Comment by bschmitz9** [comment]
@dolson334 that's not what is being passed back at all. The logo is deleting as it should and correctly showing the resort name in the main site if the logo is deleted. The object being passed back is the exact same object that is passed back when a resort or fishing photo is deleted. There are 6 unrelated tickets sitting there for you.

```
token: 'aksdjfaksd;jfasijioe;jfia;klefjae'
updates:
           modified: {}
           selected:  {
                   storyId: "0", 
                   FISHING_PICS_CACHE_NAME: "fishingPictures",     
                    etc.                       
               }
           type: "deleting"
```

**Comment by dolson334** [comment]
@bschmitz9 When adding a new logo I need something that tells me its the logo. In the picture with the base64 can you also send back "key":"logo"? Ive hard coded it for now so it works.

**Comment by bschmitz9** [comment]
@dolson334 ok I added "key: logo" to the item object. So it looks like this:

```
token: "eyJraWQiOiJtb29zZUxha2UiLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkb2xzb24zMzRAZ21haWwuY29tc3VjY2VzczIzNDkwOjA6MDowOjA6MDowOjEiLCJleHAiOjE1NjYzNjA1OTIsImlhdCI6MTU2NjM1NzU5Mn0.8w5rGNJTwKS82qn1Cf9VHPoIfL0NcLu46PvHsY7f8K8"
updates:
    item: {
           picture: "/9j/4AAQSkZJRgABAQEASABIAAD/4gxYSUNDX1BST0ZJTEUAAQ… rMuWwy56Hr61BrFlszmUIG47ACis57pAq/MB6ZooBzS6H/9k=", 
           key: "logo"
     },
    type: "save-new"
```

But it still doesn't get the picture in the preview site. This line is returning false:
`this.logo = this.utilitiesService.getPicture("logo", this.resort);`

**Comment by dolson334** [comment]
@bschmitz9 pull
