### ISSUE TITLE
New Logo Bug

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#394]
@bschmitz9 when you add a new logo and go to the staging site the new logo doesnt show and red text says "background image pending".

**Comment by bschmitz9** [comment]
@dolson334 because the logo isn't present in the preview page. This line returns false:
`this.logo = this.utilitiesService.getPicture("logo", this.resort);`

I fixed the text so that it doesn't say "background image pending"

**Comment by bschmitz9** [comment]
@dolson334 I'm closing this. This issue is related #392
