### ISSUE TITLE
Add About Us Video after deleting it

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#396]
Set up functionality to delete the about us video and then have the ability to add a new one given this is optional.

**Comment by bschmitz9** [comment]
@dolson334 this one is ready for you to look at as well. Endpoint is breaking but I expected that.

**Comment by dolson334** [comment]
@bschmitz9 When I delete... then click the add button I get this javascript error. 
```

AboutAdminComponent.html:109 ERROR TypeError: _co.showEditModal is not a function
    at Object.eval [as handleEvent] (AboutAdminComponent.html:111)
    at handleEvent (core.es5.js?de3d:12014)
    at callWithDebugContext (core.es5.js?de3d:13475)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js?de3d:13063)
    at dispatchEvent (core.es5.js?de3d:8607)
    at eval (core.es5.js?de3d:9218)
    at HTMLButtonElement.eval (platform-browser.es5.js?41b7:2651)
    at ZoneDelegate.invokeTask (zone.js?6524:425)
    at Object.onInvokeTask (core.es5.js?de3d:3881)
    at ZoneDelegate.invokeTask (zone.js?6524:424)
    at Zone.runTa
```

**Comment by bschmitz9** [comment]
@dolson334 pull.

**Comment by dolson334** [comment]
@bschmitz9 same issue here where the base64 is not being sent back for the video. Ill take a lok at he JS but you should also. Something must have changed.

**Comment by bschmitz9** [comment]
@dolson334 ok fixed

**Comment by dolson334** [comment]
@bschmitz9 I have his fixed but I broke the build ... dont pull my latest. Working on it.

**Comment by dolson334** [comment]
@bschmitz9 there is no selected object. Also, can you change the modified from "video" to "addedVideo" for consistency?

**Comment by bschmitz9** [comment]
@dolson334 right its a new video. I added a key.

**Comment by bschmitz9** [comment]
@dolson334 updating an existing video isn't working. I need that to work before I can look at the add new video.

**Comment by davidOlsonSpfcu** [comment]
@bschmitz9 why even have an update? Seems like this should be the same as a unit video. Where they add and delete ?

**Comment by bschmitz9** [comment]
@dolson334  I'm not sure what you mean. They are the same. You can delete a unit video. And then add one later. The idea is for the resort to be able to remove a video and then add another one in the future if they don't want to update right away. I don't see the video being removed on my end.

**Comment by dolson334** [comment]
@bschmitz9 I would remove the option to update. I would say they can delete and add new and thats it.  You cant update a unit video.

**Comment by bschmitz9** [comment]
@dolson334 ok so now you have to delete the video, and then you can add a new one. We are pretty close with the update video so I just commented that code out in case we want that functionality later. But adding a new video still breaks.

**Comment by dolson334** [comment]
@bschmitz9 ok working. But new video is not red in main site.
