### ISSUE TITLE
Edit Existing Unit to Have a New Video

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#397]
I'm not sure if editing an existing unit to have a new video ever worked  (I thought it was but it wasn't working at all on my end when I tested) but I updated that functionality so its getting the newly updated video. Endpoint is breaking though. I did it the same way its passed back when you add a video to a new unit as that looks to be working.

**Comment by bschmitz9** [comment]
@dolson334 I think GitHub is down or something I can't assign this to you. But this is for you.

**Comment by dolson334** [comment]
@bschmitz9 this was working. The modified json object you are passing back is empty.. It used to have the video in modified within "addedVideo"

**Comment by bschmitz9** [comment]
@dolson334 forgot to push. Pull now this is fixed.

**Comment by bschmitz9** [comment]
@dolson334 I don't think this was ever working man. I thought so too but I pulled the code from a month ago and it still doesn't work. This line returns undefined, which is what was there to get the base64 value: 

`this.newVideo.mp4 = this.cleanImgString($("#editMp4FileId").attr("src"));`

```
<!-- These house the base 64 strings.. keep these hidden -->
<input type="file" id="editMp4FileId" class="form-control-file mx-auto" style="display:none">
```

Because there is no "src" attribute for a NEW video. When a unit is updating their unit they first have to delete a video and then add a new one, so there essentially is not an existing one.

So this functionality should essentially be the same as a Unit adding a video when they are creating the Unit initially. Does that work?

**Comment by dolson334** [comment]
@bschmitz9 this definitely was working because I added back end ode specifically for this. need the base64 value passed back from the new video instead of what is being passed back now which is 

```
{
    mp4=blob:http://localhost:4200/a25bfa42-ad43-4c19-a8e4-718ac6989c31
}
```

**Comment by bschmitz9** [comment]
@dolson334 I removed this line from that function a couple weeks ago:

`this.convertFileToBase64(file, "#editMp4FileId");`
