### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#399]
What exactly do you need for this?

**Comment by dolson334** [comment]
@bschmitz9 ok it should run clean now. 

At a high level Its doing this:
1. Creating the front end dist files
2. copying those files to the Tomcat Server (specifically C:\bantor\Tomcat\Tomcat9\webapps\ROOT)
3. building the backend .war file
4. copying the war file into the tomcat server  (specifically C:\bantor\Tomcat\Tomcat9\webapps). 

then when you launch tomcat it unpacks everything and launches the server. It should load in the url localhost:8080

Ideally, we could bundle the dist files inside the java war.. I know that possible but havnt been able to make it happen.
