### ISSUE TITLE
Boat Pictures

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#400]
Any ideas where we can get some good boat pictures? We shouldn't really use pictures off of Google. Haven't been able to find anything. The other pages are good to go I think.

**Comment by dolson334** [comment]
@bschmitz9 where else would you get them if not from the internet?

This site has some good pictures https://www.rangerboats.com

**Comment by bschmitz9** [comment]
@dolson334 yes online. But all of the other pictures are from royalty free websites where they give you permission to use them. We can start by using some pictures from other companies but we'll eventually want to stop that and either get our own or see if we can use another resort's in our demo.
