### ISSUE TITLE
Updating a logo doesn't work

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#401]
@dolson334 updating a logo isn't triggering the preview change button. What do you want to do with this? Only allow delete and then add new? 

I thought we had the update functionality working here.

**Comment by dolson334** [comment]
@bschmitz9 like updating a fishing picture the modified should not have "picture" in it. its like this:

```
{
  "picture": {
    "base64": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUSEhMVFhUVFxUVFRUV..."
  }
}
```

shouldnt have the "picture" key. See the fishing pictures. I have it working though either way.
