### ISSUE TITLE
Unit Pictures

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#403]
Why do the unit pictures on the unit page double the way they are? I put 1 different main photo for each unit and then 5 different sub photos for each unit. But right now each unit has 2, 3, or 4 of the exact same picture when you click on "Learn More"

**Comment by dolson334** [comment]
@bschmitz9 are you talking when you add a new unit?

**Comment by bschmitz9** [comment]
@dolson334 No just any unit. If you click into a unit to "Learn More" the pictures are the bottom duplicate. Are you adding the same ones in there more than once? Because when I put 5 different photos in there when I was updating the photos.

**Comment by dolson334** [comment]
@bschmitz9 I really cant get this to recreate... can you give me an exact recreation path with maybe a picture?

**Comment by bschmitz9** [comment]
@dolson334 why, given these pictures in the database for the unit called "The Reserve": 

![image](https://user-images.githubusercontent.com/7662688/64734354-50ac4f80-d49b-11e9-9799-76c64b4a2ac3.png)

Does the Unit page show 4 of the same pictures:

![image](https://user-images.githubusercontent.com/7662688/64734414-720d3b80-d49b-11e9-9c47-a1b2da97765b.png)

**Comment by dolson334** [comment]
@bschmitz9  I think this may be a caching issue. Should know more soon.

**Comment by dolson334** [comment]
@bschmitz9 figured this out. Should work now.
