### ISSUE TITLE
Why does main photo show twice

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#408]
Is the main photo supposed to show twice on the staging site. 

<img width="794" alt="pic" src="https://user-images.githubusercontent.com/16144247/64577656-ac16fa00-d342-11e9-82c6-4b008d4af22f.png">

**Comment by bschmitz9** [comment]
@dolson334 Yea thats the way the code is written right now. We can skip the first photo at the bottom if it looks too repetitive.

**Comment by bschmitz9** [comment]
I updated this.
