### ISSUE TITLE
Newsletter Sign-Up in Footer / Contact-Us Form

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#409]
Does this work? 

Right now we are passing the resort's token back to the endpoint in the footer component and the contact us form, but isn't that value coming back as undefined unless a resort is logged in and saving an update:

```
public sendNewsletterInfo(firstName: string, email: string) {
		this.savingInfo = true;
		this.footerService.sendContactInfo(**this.resort.token**, firstName, email).subscribe(response => {
			this.savingInfo = false;
			this.savingError = false;
			this.savingSuccess = true;
			this.firstName = "";
			this.email = "";
		}, error => {
			this.savingInfo = false;
			this.savingError = true;
			this.savingSuccess = false;
		});
	}
```
If a normal user / customer comes and searches the website (doesn't log in) we don't have the token value do we? We aren't setting the token or resortLight until the resort logs in. 

In the production build and in Internet Explorer the resortLight is null, its not set, in the footer component when you go to a page in the main site. Which is an error we don't see in Chrome dev mode. I fixed that error but want to make sure the newlsetter sign up in the footer and the contact form is working.

**Comment by davidOlsonSpfcu** [comment]
@bschmitz9 yes... no token when on the normal site. Ill look at this in a minute

**Comment by dolson334** [comment]
@bschmitz9 I guess I dont see what your looking for here. What do you want me to verify?

**Comment by bschmitz9** [comment]
@dolson334 does it work? Can you send a contact message and get it sent to the right place?

Can you put your name and email into the newsletter signup in the footer and does it add that user to that resort's list in the database? How do you know which resort you are adding the user to if you don't know the token?

I want to make sure they work correctly

**Comment by dolson334** [comment]
@bschmitz9 In the main site we are not passing back a token. Instead I get the resort from the URL. So when we go live Ill look at the domain of the request (if its vdl.com Ill know its that resort).

The contact us is working. Just entered your email for one.

**Comment by dolson334** [comment]
@bschmitz9 just sent you a newsletter. These are both working as intended. There are contact us and newsletter records in the database.
