### ISSUE TITLE
Units: Adding a video with a new unit

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#416]
1. Add a video when creating a new unit.
2. Go to the Unit page in the preview site - the video just shows black.
3. Approve the unit and then try to edit the video in the admin site - no video appears.

**Comment by dolson334** [comment]
@bschmitz9 This exists in Prod and Dev. This is because in this scenario you are passing back the blob url 

```
video: {
     "mp4":"blob:http://localhost:4200/b644c597-3884-4c3d-81f2-46b9ffd510ff"
}
```

If you delete and add a video for an existing unit the base64 is passed back like it should be.

**Comment by bschmitz9** [comment]
@dolson334 alright check this. I changed the property from "mp4" to "base64
