### ISSUE TITLE
Updating About Us Pictures Breaks endpoint

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#419]

**Comment by bschmitz9** [comment]
Update any of the photos on the about us and the endpoint breaks.

**Comment by dolson334** [comment]
@bschmitz9  #423 needs to be fixed first

**Comment by dolson334** [comment]
#431 needs to be fixed first.

**Comment by dolson334** [comment]
@bschmitz9 A couple of these prod ones are the same issue. Im looking at it.

**Comment by dolson334** [comment]
@bschmitz9 try this too
