### ISSUE TITLE
Verify the New Db Env Creation button works

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#42]
follow the new doc at ..

bantor\bantorDocs\Creating a new Local Database Environment.docx

make sure when you are done the following exists in your sql server:
1. a database called 'bantor'
2. a database called 'bantorAdmin'
3. ensure each database has tables and that the tables have data (dont have to check them all just a few)

**Comment by dolson55** [comment]
Ill get this done as quick as I can.  Have a couple of exams this week and for some reason my Tomcat won't run again so I need to fix that.

**Comment by dolson334** [comment]
@dolson55 when will you have some free time? When are your finals done. Dont screw with that.
