### ISSUE TITLE
About Us: updating any photo on page breaks endpoint

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#423]
Updating employee photo, features intro photo, or features row photo doesn't work

**Comment by dolson334** [comment]
@bschmitz9 the Id in the modified is what is causing this to break. That shouldnt be there. Were not modifying the id so it shouldnt be in the modified. 

```
modified:
id: 3
picture: {id: 98, base64: "iVBORw0KGgoAAAANSUhEUgAAAkQAAAHfCAIAAAA+y1AQAAAAAX…wrOYDG4zGR1hm/+f//P8Bk6SkRetDJ3MAAAAASUVORK5CYII="}
__proto__: Object
```

**Comment by dolson334** [comment]
@bschmitz9 my comment above was for employee.
