### ISSUE TITLE
Contact Us: Updating social media link breaks page

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#430]

**Comment by bschmitz9** [comment]
for preview enabled and not enabled

**Comment by dolson334** [comment]
@bschmitz9 I cant recreate this. May be fixed with some of my latest changes

**Comment by bschmitz9** [comment]
@dolson334 yea these don't work for me I get a 500 error for all of them. Updating one social media link at a time. If you can't recreate then just close it and we'll test it again when its up online.
