### ISSUE TITLE
Updated About Us Photo

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#431]
Updating any of the About Us photos doesn't delete the old photo. So when you update a photo there is an additional photo in the pictures array. 

Also, make sure the isStaged is being flipped to true. Not the isNew.

**Comment by dolson334** [comment]
@bschmitz9 when updating a features intro picture.. the modified does not have the picture id that we are updating. 
should be
 ```

modified: 
{
    picture:
    {
     id: 23, 
     base64: hlkjhlkjhkjhklhj.....

    }

}
```

**Comment by bschmitz9** [comment]
@dolson334 I just took the id out. I put it back in. It's still missing the dir value in the stagedValues object. Also, make sure isStaged is getting updated to true. Right now "isTrue" is changing. These are updated pictures so isStaged should be getting updated not isNew

**Comment by dolson334** [comment]
@bschmitz9 the id is not in the modified json for features and employees. I just checked.

**Comment by bschmitz9** [comment]
@dolson334 it is now. Pull
