### ISSUE TITLE
Edit Boat to have a new main photo removes previous photo in admin

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#434]
1. Edit an existing boat to have a new photo.
2. Make the new photo the main photo. 
3. Save
4. The resort loses its main picture in the admin site. 

All photos have "isMain" set to false after saving.

It works after you go through and approve the update but right after saving the update the photo breaks.

**Comment by bschmitz9** [comment]
This works fine when preview is disabled.

**Comment by dolson334** [comment]
@bschmitz9 pull and try this.
