### ISSUE TITLE
About Us Page Add's 2 Videos

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#436]
On the about us if you delete the video and then add another one, it puts two pending videos on the preview page. So if you approve or decline the first one, the second video added shows as pending as well.

1. Delete Video in admin
2. Add a new video
3. Add another new video without approving the first one.
4. Go to the preview:
       If you approve the video, the preview reloads the preview site when there are no more pending changes
       If you decline the video, the preview reloads with the approval buttons showing for the second video added

Just take whatever video is added last and make that the only video pending.

**Comment by dolson334** [comment]
@bschmitz9 Pull and try now.
