### ISSUE TITLE
Figure out why Brian's Community pages dont work

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#8]
Mine work.  His dont.  Figure it out. 

@bschmitz9 these are working for me. See if you can run incognito and still have this issue.  if still not running see if there is a console error.  If so, paste it in here and reassign to me.

**Comment by dolson334** [comment]
@dolson55 @bschmitz9  this must be some kind of java error going to the database since this is working for me.  Can you post the error you are seeing in the console in here?

**Comment by dolson55** [comment]
Well now my community webpage isn't even loading.... Are you guys having this issue?

**Comment by dolson334** [comment]
@dolson55 are you using the mac? There is no community page its only one of the dropdowns.  Does Blog load anything? any error in your console?

**Comment by dolson55** [comment]
I'm on my mac but using my windows utility.  I'll attach a screenshot of my console.

**Comment by dolson55** [comment]
![capture](https://cloud.githubusercontent.com/assets/20147168/17314785/6d6c1bc6-582c-11e6-9ff8-7250bc32498b.PNG)

**Comment by dolson55** [comment]
I don't think I'm even getting any error messages in regards to community.  Just looks like Tomcat messages.
